/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.ui.contentassist;

import org.xtuml.bp.xtext.ui.contentassist.AbstractMaslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MaslProposalProvider extends AbstractMaslProposalProvider {
}
