/*
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.ISetup;
import org.eclipse.xtext.common.TerminalsStandaloneSetup;
import org.eclipse.xtext.resource.IResourceFactory;
import org.eclipse.xtext.resource.IResourceServiceProvider;
import org.xtuml.bp.xtext.masl.MaslPackage;

@SuppressWarnings("all")
public class MaslStandaloneSetupGenerated implements ISetup {

	@Override
	public Injector createInjectorAndDoEMFRegistration() {
		TerminalsStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}
	
	public Injector createInjector() {
		return Guice.createInjector(new MaslRuntimeModule());
	}
	
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.xtuml.org/bp/xtext/Masl")) {
			EPackage.Registry.INSTANCE.put("http://www.xtuml.org/bp/xtext/Masl", MaslPackage.eINSTANCE);
		}
		IResourceFactory resourceFactory = injector.getInstance(IResourceFactory.class);
		IResourceServiceProvider serviceProvider = injector.getInstance(IResourceServiceProvider.class);
		
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("masl", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("masl", serviceProvider);
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("prj", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("prj", serviceProvider);
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("mod", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("mod", serviceProvider);
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("tr", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("tr", serviceProvider);
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("svc", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("svc", serviceProvider);
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("scn", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("scn", serviceProvider);
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("al", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("al", serviceProvider);
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("int", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("int", serviceProvider);
	}
}
