/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtuml.bp.xtext.ui.AbstractMaslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MaslUiModule extends AbstractMaslUiModule {
  public MaslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
