/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.scoping;

import org.xtuml.bp.xtext.scoping.AbstractMaslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MaslScopeProvider extends AbstractMaslScopeProvider {
}
