/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.tests;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtuml.bp.xtext.masl.Project;
import org.xtuml.bp.xtext.tests.MaslInjectorProvider;

@RunWith(XtextRunner.class)
@InjectWith(MaslInjectorProvider.class)
@SuppressWarnings("all")
public class MaslParsingTest {
  @Inject
  private ParseHelper<Project> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final Project result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
