/*
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMaslScopeProvider extends DelegatingScopeProvider {
}
