/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext;

import org.xtuml.bp.xtext.AbstractMaslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MaslRuntimeModule extends AbstractMaslRuntimeModule {
}
