/*
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MaslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ProjectDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.projectDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPROJECTParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cProjectNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cProjectNameProjectNameParserRuleCall_1_0 = (RuleCall)cProjectNameAssignment_1.eContents().get(0);
		private final RuleCall cISParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cProjectItemAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cProjectItemProjectItemParserRuleCall_3_0 = (RuleCall)cProjectItemAssignment_3.eContents().get(0);
		private final RuleCall cENDParserRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final RuleCall cPROJECTParserRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final RuleCall cSEMIParserRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		private final Assignment cPragmaListAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPragmaListPragmaListParserRuleCall_7_0 = (RuleCall)cPragmaListAssignment_7.eContents().get(0);
		
		////target                        : projectDefinition+;
		////---------------------------------------------------------
		//// Project Definition
		////---------------------------------------------------------
		//projectDefinition Project:
		//	PROJECT projectName=projectName IS
		//	projectItem+=projectItem*
		//	END PROJECT? SEMI pragmaList=pragmaList
		@Override public ParserRule getRule() { return rule; }
		
		//PROJECT projectName=projectName IS projectItem+=projectItem* END PROJECT? SEMI pragmaList=pragmaList
		public Group getGroup() { return cGroup; }
		
		//PROJECT
		public RuleCall getPROJECTParserRuleCall_0() { return cPROJECTParserRuleCall_0; }
		
		//projectName=projectName
		public Assignment getProjectNameAssignment_1() { return cProjectNameAssignment_1; }
		
		//projectName
		public RuleCall getProjectNameProjectNameParserRuleCall_1_0() { return cProjectNameProjectNameParserRuleCall_1_0; }
		
		//IS
		public RuleCall getISParserRuleCall_2() { return cISParserRuleCall_2; }
		
		//projectItem+=projectItem*
		public Assignment getProjectItemAssignment_3() { return cProjectItemAssignment_3; }
		
		//projectItem
		public RuleCall getProjectItemProjectItemParserRuleCall_3_0() { return cProjectItemProjectItemParserRuleCall_3_0; }
		
		//END
		public RuleCall getENDParserRuleCall_4() { return cENDParserRuleCall_4; }
		
		//PROJECT?
		public RuleCall getPROJECTParserRuleCall_5() { return cPROJECTParserRuleCall_5; }
		
		//SEMI
		public RuleCall getSEMIParserRuleCall_6() { return cSEMIParserRuleCall_6; }
		
		//pragmaList=pragmaList
		public Assignment getPragmaListAssignment_7() { return cPragmaListAssignment_7; }
		
		//pragmaList
		public RuleCall getPragmaListPragmaListParserRuleCall_7_0() { return cPragmaListPragmaListParserRuleCall_7_0; }
	}
	public class ProjectItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.projectItem");
		private final RuleCall cDomainPrjDefinitionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//projectItem:
		//	domainPrjDefinition;
		@Override public ParserRule getRule() { return rule; }
		
		//domainPrjDefinition
		public RuleCall getDomainPrjDefinitionParserRuleCall() { return cDomainPrjDefinitionParserRuleCall; }
	}
	public class DomainPrjDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.domainPrjDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cDOMAINParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cDomainNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDomainNameDomainNameParserRuleCall_1_0 = (RuleCall)cDomainNameAssignment_1.eContents().get(0);
		private final RuleCall cISParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cDomainPrjItemAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDomainPrjItemDomainPrjItemParserRuleCall_3_0 = (RuleCall)cDomainPrjItemAssignment_3.eContents().get(0);
		private final RuleCall cENDParserRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final RuleCall cDOMAINParserRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final RuleCall cSEMIParserRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		private final Assignment cPragmaListAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPragmaListPragmaListParserRuleCall_7_0 = (RuleCall)cPragmaListAssignment_7.eContents().get(0);
		
		//domainPrjDefinition Domain:
		//	DOMAIN domainName=domainName IS
		//	domainPrjItem+=domainPrjItem*
		//	END DOMAIN? SEMI pragmaList=pragmaList
		@Override public ParserRule getRule() { return rule; }
		
		//DOMAIN domainName=domainName IS domainPrjItem+=domainPrjItem* END DOMAIN? SEMI pragmaList=pragmaList
		public Group getGroup() { return cGroup; }
		
		//DOMAIN
		public RuleCall getDOMAINParserRuleCall_0() { return cDOMAINParserRuleCall_0; }
		
		//domainName=domainName
		public Assignment getDomainNameAssignment_1() { return cDomainNameAssignment_1; }
		
		//domainName
		public RuleCall getDomainNameDomainNameParserRuleCall_1_0() { return cDomainNameDomainNameParserRuleCall_1_0; }
		
		//IS
		public RuleCall getISParserRuleCall_2() { return cISParserRuleCall_2; }
		
		//domainPrjItem+=domainPrjItem*
		public Assignment getDomainPrjItemAssignment_3() { return cDomainPrjItemAssignment_3; }
		
		//domainPrjItem
		public RuleCall getDomainPrjItemDomainPrjItemParserRuleCall_3_0() { return cDomainPrjItemDomainPrjItemParserRuleCall_3_0; }
		
		//END
		public RuleCall getENDParserRuleCall_4() { return cENDParserRuleCall_4; }
		
		//DOMAIN?
		public RuleCall getDOMAINParserRuleCall_5() { return cDOMAINParserRuleCall_5; }
		
		//SEMI
		public RuleCall getSEMIParserRuleCall_6() { return cSEMIParserRuleCall_6; }
		
		//pragmaList=pragmaList
		public Assignment getPragmaListAssignment_7() { return cPragmaListAssignment_7; }
		
		//pragmaList
		public RuleCall getPragmaListPragmaListParserRuleCall_7_0() { return cPragmaListPragmaListParserRuleCall_7_0; }
	}
	public class DomainPrjItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.domainPrjItem");
		private final RuleCall cTerminatorDefinitionParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//domainPrjItem:
		//	terminatorDefinition;
		@Override public ParserRule getRule() { return rule; }
		
		//terminatorDefinition
		public RuleCall getTerminatorDefinitionParserRuleCall() { return cTerminatorDefinitionParserRuleCall; }
	}
	public class ProjectNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.projectName");
		private final Assignment cIdentifierAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cIdentifierIDTerminalRuleCall_0 = (RuleCall)cIdentifierAssignment.eContents().get(0);
		
		//projectName ProjectName:
		//	identifier=ID
		@Override public ParserRule getRule() { return rule; }
		
		//identifier=ID
		public Assignment getIdentifierAssignment() { return cIdentifierAssignment; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_0() { return cIdentifierIDTerminalRuleCall_0; }
	}
	public class DomainNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.domainName");
		private final Assignment cIdentifierAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cIdentifierIDTerminalRuleCall_0 = (RuleCall)cIdentifierAssignment.eContents().get(0);
		
		//domainName DomainName:
		//	identifier=ID
		@Override public ParserRule getRule() { return rule; }
		
		//identifier=ID
		public Assignment getIdentifierAssignment() { return cIdentifierAssignment; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_0() { return cIdentifierIDTerminalRuleCall_0; }
	}
	public class TerminatorNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.terminatorName");
		private final Assignment cIdentifierAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cIdentifierIDTerminalRuleCall_0 = (RuleCall)cIdentifierAssignment.eContents().get(0);
		
		////---------------------------------------------------------
		//// Terminator Definition
		////---------------------------------------------------------
		//terminatorName TerminatorName:
		//	identifier=ID
		@Override public ParserRule getRule() { return rule; }
		
		//identifier=ID
		public Assignment getIdentifierAssignment() { return cIdentifierAssignment; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_0() { return cIdentifierIDTerminalRuleCall_0; }
	}
	public class TerminatorDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.terminatorDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cTERMINATORParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cTerminatorNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTerminatorNameTerminatorNameParserRuleCall_1_0 = (RuleCall)cTerminatorNameAssignment_1.eContents().get(0);
		private final RuleCall cISParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cTerminatorItemAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTerminatorItemTerminatorItemParserRuleCall_3_0 = (RuleCall)cTerminatorItemAssignment_3.eContents().get(0);
		private final RuleCall cENDParserRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final RuleCall cTERMINATORParserRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final RuleCall cSEMIParserRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		private final Assignment cPragmaListAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPragmaListPragmaListParserRuleCall_7_0 = (RuleCall)cPragmaListAssignment_7.eContents().get(0);
		
		//terminatorDefinition TerminatorDefinition:
		//	TERMINATOR terminatorName=terminatorName IS
		//	terminatorItem+=terminatorItem*
		//	END TERMINATOR? SEMI pragmaList=pragmaList
		@Override public ParserRule getRule() { return rule; }
		
		//TERMINATOR terminatorName=terminatorName IS terminatorItem+=terminatorItem* END TERMINATOR? SEMI pragmaList=pragmaList
		public Group getGroup() { return cGroup; }
		
		//TERMINATOR
		public RuleCall getTERMINATORParserRuleCall_0() { return cTERMINATORParserRuleCall_0; }
		
		//terminatorName=terminatorName
		public Assignment getTerminatorNameAssignment_1() { return cTerminatorNameAssignment_1; }
		
		//terminatorName
		public RuleCall getTerminatorNameTerminatorNameParserRuleCall_1_0() { return cTerminatorNameTerminatorNameParserRuleCall_1_0; }
		
		//IS
		public RuleCall getISParserRuleCall_2() { return cISParserRuleCall_2; }
		
		//terminatorItem+=terminatorItem*
		public Assignment getTerminatorItemAssignment_3() { return cTerminatorItemAssignment_3; }
		
		//terminatorItem
		public RuleCall getTerminatorItemTerminatorItemParserRuleCall_3_0() { return cTerminatorItemTerminatorItemParserRuleCall_3_0; }
		
		//END
		public RuleCall getENDParserRuleCall_4() { return cENDParserRuleCall_4; }
		
		//TERMINATOR?
		public RuleCall getTERMINATORParserRuleCall_5() { return cTERMINATORParserRuleCall_5; }
		
		//SEMI
		public RuleCall getSEMIParserRuleCall_6() { return cSEMIParserRuleCall_6; }
		
		//pragmaList=pragmaList
		public Assignment getPragmaListAssignment_7() { return cPragmaListAssignment_7; }
		
		//pragmaList
		public RuleCall getPragmaListPragmaListParserRuleCall_7_0() { return cPragmaListPragmaListParserRuleCall_7_0; }
	}
	public class TerminatorItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.terminatorItem");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTerminatorServiceDeclarationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTerminatorFunctionDeclarationParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//terminatorItem:
		//	terminatorServiceDeclaration
		//	| terminatorFunctionDeclaration;
		@Override public ParserRule getRule() { return rule; }
		
		//terminatorServiceDeclaration | terminatorFunctionDeclaration
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//terminatorServiceDeclaration
		public RuleCall getTerminatorServiceDeclarationParserRuleCall_0() { return cTerminatorServiceDeclarationParserRuleCall_0; }
		
		//terminatorFunctionDeclaration
		public RuleCall getTerminatorFunctionDeclarationParserRuleCall_1() { return cTerminatorFunctionDeclarationParserRuleCall_1; }
	}
	public class TerminatorServiceDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.terminatorServiceDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cServiceVisibilityAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cServiceVisibilityServiceVisibilityParserRuleCall_0_0 = (RuleCall)cServiceVisibilityAssignment_0.eContents().get(0);
		private final RuleCall cSERVICEParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cServiceNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cServiceNameServiceNameParserRuleCall_2_0 = (RuleCall)cServiceNameAssignment_2.eContents().get(0);
		private final Assignment cParameterListAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cParameterListParameterListParserRuleCall_3_0 = (RuleCall)cParameterListAssignment_3.eContents().get(0);
		private final RuleCall cSEMIParserRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Assignment cPragmaListAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPragmaListPragmaListParserRuleCall_5_0 = (RuleCall)cPragmaListAssignment_5.eContents().get(0);
		
		//terminatorServiceDeclaration TerminatorServiceDeclaration:
		//	serviceVisibility=serviceVisibility SERVICE serviceName=serviceName
		//	parameterList=parameterList SEMI pragmaList=pragmaList
		@Override public ParserRule getRule() { return rule; }
		
		//serviceVisibility=serviceVisibility SERVICE serviceName=serviceName parameterList=parameterList SEMI
		//pragmaList=pragmaList
		public Group getGroup() { return cGroup; }
		
		//serviceVisibility=serviceVisibility
		public Assignment getServiceVisibilityAssignment_0() { return cServiceVisibilityAssignment_0; }
		
		//serviceVisibility
		public RuleCall getServiceVisibilityServiceVisibilityParserRuleCall_0_0() { return cServiceVisibilityServiceVisibilityParserRuleCall_0_0; }
		
		//SERVICE
		public RuleCall getSERVICEParserRuleCall_1() { return cSERVICEParserRuleCall_1; }
		
		//serviceName=serviceName
		public Assignment getServiceNameAssignment_2() { return cServiceNameAssignment_2; }
		
		//serviceName
		public RuleCall getServiceNameServiceNameParserRuleCall_2_0() { return cServiceNameServiceNameParserRuleCall_2_0; }
		
		//parameterList=parameterList
		public Assignment getParameterListAssignment_3() { return cParameterListAssignment_3; }
		
		//parameterList
		public RuleCall getParameterListParameterListParserRuleCall_3_0() { return cParameterListParameterListParserRuleCall_3_0; }
		
		//SEMI
		public RuleCall getSEMIParserRuleCall_4() { return cSEMIParserRuleCall_4; }
		
		//pragmaList=pragmaList
		public Assignment getPragmaListAssignment_5() { return cPragmaListAssignment_5; }
		
		//pragmaList
		public RuleCall getPragmaListPragmaListParserRuleCall_5_0() { return cPragmaListPragmaListParserRuleCall_5_0; }
	}
	public class TerminatorFunctionDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.terminatorFunctionDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cServiceVisibilityAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cServiceVisibilityServiceVisibilityParserRuleCall_0_0 = (RuleCall)cServiceVisibilityAssignment_0.eContents().get(0);
		private final RuleCall cFUNCTIONParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cServiceNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cServiceNameServiceNameParserRuleCall_2_0 = (RuleCall)cServiceNameAssignment_2.eContents().get(0);
		private final Assignment cParameterListAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cParameterListParameterListParserRuleCall_3_0 = (RuleCall)cParameterListAssignment_3.eContents().get(0);
		private final RuleCall cRETURNParserRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Assignment cReturnTypeAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cReturnTypeReturnTypeParserRuleCall_5_0 = (RuleCall)cReturnTypeAssignment_5.eContents().get(0);
		private final RuleCall cSEMIParserRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		private final Assignment cPragmaListAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPragmaListPragmaListParserRuleCall_7_0 = (RuleCall)cPragmaListAssignment_7.eContents().get(0);
		
		//terminatorFunctionDeclaration TerminatorFunctionDeclaration:
		//	serviceVisibility=serviceVisibility FUNCTION serviceName=serviceName
		//	parameterList=parameterList RETURN returnType=returnType
		//	SEMI pragmaList=pragmaList
		@Override public ParserRule getRule() { return rule; }
		
		//serviceVisibility=serviceVisibility FUNCTION serviceName=serviceName parameterList=parameterList RETURN
		//returnType=returnType SEMI pragmaList=pragmaList
		public Group getGroup() { return cGroup; }
		
		//serviceVisibility=serviceVisibility
		public Assignment getServiceVisibilityAssignment_0() { return cServiceVisibilityAssignment_0; }
		
		//serviceVisibility
		public RuleCall getServiceVisibilityServiceVisibilityParserRuleCall_0_0() { return cServiceVisibilityServiceVisibilityParserRuleCall_0_0; }
		
		//FUNCTION
		public RuleCall getFUNCTIONParserRuleCall_1() { return cFUNCTIONParserRuleCall_1; }
		
		//serviceName=serviceName
		public Assignment getServiceNameAssignment_2() { return cServiceNameAssignment_2; }
		
		//serviceName
		public RuleCall getServiceNameServiceNameParserRuleCall_2_0() { return cServiceNameServiceNameParserRuleCall_2_0; }
		
		//parameterList=parameterList
		public Assignment getParameterListAssignment_3() { return cParameterListAssignment_3; }
		
		//parameterList
		public RuleCall getParameterListParameterListParserRuleCall_3_0() { return cParameterListParameterListParserRuleCall_3_0; }
		
		//RETURN
		public RuleCall getRETURNParserRuleCall_4() { return cRETURNParserRuleCall_4; }
		
		//returnType=returnType
		public Assignment getReturnTypeAssignment_5() { return cReturnTypeAssignment_5; }
		
		//returnType
		public RuleCall getReturnTypeReturnTypeParserRuleCall_5_0() { return cReturnTypeReturnTypeParserRuleCall_5_0; }
		
		//SEMI
		public RuleCall getSEMIParserRuleCall_6() { return cSEMIParserRuleCall_6; }
		
		//pragmaList=pragmaList
		public Assignment getPragmaListAssignment_7() { return cPragmaListAssignment_7; }
		
		//pragmaList
		public RuleCall getPragmaListPragmaListParserRuleCall_7_0() { return cPragmaListPragmaListParserRuleCall_7_0; }
	}
	public class ParameterListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.parameterList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cLPARENParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cParameterDefinitionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cParameterDefinitionParameterDefinitionParserRuleCall_1_0 = (RuleCall)cParameterDefinitionAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final RuleCall cCOMMAParserRuleCall_2_0 = (RuleCall)cGroup_2.eContents().get(0);
		private final Assignment cParameterDefinitionAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cParameterDefinitionParameterDefinitionParserRuleCall_2_1_0 = (RuleCall)cParameterDefinitionAssignment_2_1.eContents().get(0);
		private final RuleCall cRPARENParserRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//parameterList:
		//	LPAREN
		//	parameterDefinition+=parameterDefinition? (COMMA parameterDefinition+=parameterDefinition)*
		//	RPAREN;
		@Override public ParserRule getRule() { return rule; }
		
		//LPAREN parameterDefinition+=parameterDefinition? (COMMA parameterDefinition+=parameterDefinition)* RPAREN
		public Group getGroup() { return cGroup; }
		
		//LPAREN
		public RuleCall getLPARENParserRuleCall_0() { return cLPARENParserRuleCall_0; }
		
		//parameterDefinition+=parameterDefinition?
		public Assignment getParameterDefinitionAssignment_1() { return cParameterDefinitionAssignment_1; }
		
		//parameterDefinition
		public RuleCall getParameterDefinitionParameterDefinitionParserRuleCall_1_0() { return cParameterDefinitionParameterDefinitionParserRuleCall_1_0; }
		
		//(COMMA parameterDefinition+=parameterDefinition)*
		public Group getGroup_2() { return cGroup_2; }
		
		//COMMA
		public RuleCall getCOMMAParserRuleCall_2_0() { return cCOMMAParserRuleCall_2_0; }
		
		//parameterDefinition+=parameterDefinition
		public Assignment getParameterDefinitionAssignment_2_1() { return cParameterDefinitionAssignment_2_1; }
		
		//parameterDefinition
		public RuleCall getParameterDefinitionParameterDefinitionParserRuleCall_2_1_0() { return cParameterDefinitionParameterDefinitionParserRuleCall_2_1_0; }
		
		//RPAREN
		public RuleCall getRPARENParserRuleCall_3() { return cRPARENParserRuleCall_3; }
	}
	public class ParameterDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.parameterDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cParameterNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cParameterNameParameterNameParserRuleCall_0_0 = (RuleCall)cParameterNameAssignment_0.eContents().get(0);
		private final RuleCall cCOLONParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cParameterModeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cParameterModeParameterModeParserRuleCall_2_0 = (RuleCall)cParameterModeAssignment_2.eContents().get(0);
		private final Assignment cParameterTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cParameterTypeParameterTypeParserRuleCall_3_0 = (RuleCall)cParameterTypeAssignment_3.eContents().get(0);
		
		//parameterDefinition ParameterDefinition:
		//	parameterName=parameterName COLON parameterMode=parameterMode parameterType=parameterType
		@Override public ParserRule getRule() { return rule; }
		
		//parameterName=parameterName COLON parameterMode=parameterMode parameterType=parameterType
		public Group getGroup() { return cGroup; }
		
		//parameterName=parameterName
		public Assignment getParameterNameAssignment_0() { return cParameterNameAssignment_0; }
		
		//parameterName
		public RuleCall getParameterNameParameterNameParserRuleCall_0_0() { return cParameterNameParameterNameParserRuleCall_0_0; }
		
		//COLON
		public RuleCall getCOLONParserRuleCall_1() { return cCOLONParserRuleCall_1; }
		
		//parameterMode=parameterMode
		public Assignment getParameterModeAssignment_2() { return cParameterModeAssignment_2; }
		
		//parameterMode
		public RuleCall getParameterModeParameterModeParserRuleCall_2_0() { return cParameterModeParameterModeParserRuleCall_2_0; }
		
		//parameterType=parameterType
		public Assignment getParameterTypeAssignment_3() { return cParameterTypeAssignment_3; }
		
		//parameterType
		public RuleCall getParameterTypeParameterTypeParserRuleCall_3_0() { return cParameterTypeParameterTypeParserRuleCall_3_0; }
	}
	public class ServiceVisibilityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.serviceVisibility");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPRIVATEParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPUBLICParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		/// * fix for blank * / serviceVisibility:
		//	PRIVATE
		//	| PUBLIC;
		@Override public ParserRule getRule() { return rule; }
		
		//PRIVATE | PUBLIC
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PRIVATE
		public RuleCall getPRIVATEParserRuleCall_0() { return cPRIVATEParserRuleCall_0; }
		
		//PUBLIC
		public RuleCall getPUBLICParserRuleCall_1() { return cPUBLICParserRuleCall_1; }
	}
	public class ParameterModeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.parameterMode");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cINParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cOUTParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//parameterMode:
		//	IN
		//	| OUT;
		@Override public ParserRule getRule() { return rule; }
		
		//IN | OUT
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IN
		public RuleCall getINParserRuleCall_0() { return cINParserRuleCall_0; }
		
		//OUT
		public RuleCall getOUTParserRuleCall_1() { return cOUTParserRuleCall_1; }
	}
	public class ServiceNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.serviceName");
		private final Assignment cIdentifierAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cIdentifierIDTerminalRuleCall_0 = (RuleCall)cIdentifierAssignment.eContents().get(0);
		
		//serviceName ServiceName:
		//	identifier=ID
		@Override public ParserRule getRule() { return rule; }
		
		//identifier=ID
		public Assignment getIdentifierAssignment() { return cIdentifierAssignment; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_0() { return cIdentifierIDTerminalRuleCall_0; }
	}
	public class ParameterNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.parameterName");
		private final Assignment cIdentifierAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cIdentifierIDTerminalRuleCall_0 = (RuleCall)cIdentifierAssignment.eContents().get(0);
		
		//parameterName ParameterName:
		//	identifier=ID
		@Override public ParserRule getRule() { return rule; }
		
		//identifier=ID
		public Assignment getIdentifierAssignment() { return cIdentifierAssignment; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_0() { return cIdentifierIDTerminalRuleCall_0; }
	}
	public class ParameterTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.parameterType");
		private final Assignment cTypeReferenceAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cTypeReferenceTypeReferenceParserRuleCall_0 = (RuleCall)cTypeReferenceAssignment.eContents().get(0);
		
		//parameterType ParameterType:
		//	typeReference=typeReference
		@Override public ParserRule getRule() { return rule; }
		
		//typeReference=typeReference
		public Assignment getTypeReferenceAssignment() { return cTypeReferenceAssignment; }
		
		//typeReference
		public RuleCall getTypeReferenceTypeReferenceParserRuleCall_0() { return cTypeReferenceTypeReferenceParserRuleCall_0; }
	}
	public class ReturnTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.returnType");
		private final Assignment cTypeReferenceAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cTypeReferenceTypeReferenceParserRuleCall_0 = (RuleCall)cTypeReferenceAssignment.eContents().get(0);
		
		//returnType ReturnType:
		//	typeReference=typeReference
		@Override public ParserRule getRule() { return rule; }
		
		//typeReference=typeReference
		public Assignment getTypeReferenceAssignment() { return cTypeReferenceAssignment; }
		
		//typeReference
		public RuleCall getTypeReferenceTypeReferenceParserRuleCall_0() { return cTypeReferenceTypeReferenceParserRuleCall_0; }
	}
	public class TypeReferenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.typeReference");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNamedTypeRefParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDeprecatedTypeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		////---------------------------------------------------------
		//// Type Reference
		////---------------------------------------------------------
		//typeReference:
		//	namedTypeRef
		//	| deprecatedType;
		@Override public ParserRule getRule() { return rule; }
		
		//namedTypeRef | deprecatedType
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//namedTypeRef
		public RuleCall getNamedTypeRefParserRuleCall_0() { return cNamedTypeRefParserRuleCall_0; }
		
		//deprecatedType
		public RuleCall getDeprecatedTypeParserRuleCall_1() { return cDeprecatedTypeParserRuleCall_1; }
	}
	public class DeprecatedTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.deprecatedType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cINSTANCEParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cEVENTParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSERVICEParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//deprecatedType:
		//	INSTANCE
		//	| EVENT
		//	| SERVICE;
		@Override public ParserRule getRule() { return rule; }
		
		//INSTANCE | EVENT | SERVICE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//INSTANCE
		public RuleCall getINSTANCEParserRuleCall_0() { return cINSTANCEParserRuleCall_0; }
		
		//EVENT
		public RuleCall getEVENTParserRuleCall_1() { return cEVENTParserRuleCall_1; }
		
		//SERVICE
		public RuleCall getSERVICEParserRuleCall_2() { return cSERVICEParserRuleCall_2; }
	}
	public class NamedTypeRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.namedTypeRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAnonymousAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cAnonymousANONYMOUSParserRuleCall_0_0 = (RuleCall)cAnonymousAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cDomainNameAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cDomainNameDomainNameParserRuleCall_1_0_0 = (RuleCall)cDomainNameAssignment_1_0.eContents().get(0);
		private final RuleCall cSCOPEParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cTypeNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeNameTypeNameParserRuleCall_2_0 = (RuleCall)cTypeNameAssignment_2.eContents().get(0);
		
		//namedTypeRef NamedType:
		//	anonymous=ANONYMOUS? (domainName=domainName SCOPE)? typeName=typeName
		@Override public ParserRule getRule() { return rule; }
		
		//anonymous=ANONYMOUS? (domainName=domainName SCOPE)? typeName=typeName
		public Group getGroup() { return cGroup; }
		
		//anonymous=ANONYMOUS?
		public Assignment getAnonymousAssignment_0() { return cAnonymousAssignment_0; }
		
		//ANONYMOUS
		public RuleCall getAnonymousANONYMOUSParserRuleCall_0_0() { return cAnonymousANONYMOUSParserRuleCall_0_0; }
		
		//(domainName=domainName SCOPE)?
		public Group getGroup_1() { return cGroup_1; }
		
		//domainName=domainName
		public Assignment getDomainNameAssignment_1_0() { return cDomainNameAssignment_1_0; }
		
		//domainName
		public RuleCall getDomainNameDomainNameParserRuleCall_1_0_0() { return cDomainNameDomainNameParserRuleCall_1_0_0; }
		
		//SCOPE
		public RuleCall getSCOPEParserRuleCall_1_1() { return cSCOPEParserRuleCall_1_1; }
		
		//typeName=typeName
		public Assignment getTypeNameAssignment_2() { return cTypeNameAssignment_2; }
		
		//typeName
		public RuleCall getTypeNameTypeNameParserRuleCall_2_0() { return cTypeNameTypeNameParserRuleCall_2_0; }
	}
	public class TypeNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.typeName");
		private final Assignment cIdentifierAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cIdentifierIDTerminalRuleCall_0 = (RuleCall)cIdentifierAssignment.eContents().get(0);
		
		//typeName TypeName:
		//	identifier=ID
		@Override public ParserRule getRule() { return rule; }
		
		//identifier=ID
		public Assignment getIdentifierAssignment() { return cIdentifierAssignment; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_0() { return cIdentifierIDTerminalRuleCall_0; }
	}
	public class PragmaListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.pragmaList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPragmaAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPragmaPragmaParserRuleCall_0_0 = (RuleCall)cPragmaAssignment_0.eContents().get(0);
		private final RuleCall cSEMIParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		////---------------------------------------------------------
		//// Pragma Definition
		////---------------------------------------------------------
		//pragmaList PragmaList:
		//	(pragma+=pragma SEMI)*
		@Override public ParserRule getRule() { return rule; }
		
		//(pragma+=pragma SEMI)*
		public Group getGroup() { return cGroup; }
		
		//pragma+=pragma
		public Assignment getPragmaAssignment_0() { return cPragmaAssignment_0; }
		
		//pragma
		public RuleCall getPragmaPragmaParserRuleCall_0_0() { return cPragmaPragmaParserRuleCall_0_0; }
		
		//SEMI
		public RuleCall getSEMIParserRuleCall_1() { return cSEMIParserRuleCall_1; }
	}
	public class PragmaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.pragma");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPRAGMATOKParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cPragmaNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPragmaNamePragmaNameParserRuleCall_1_0 = (RuleCall)cPragmaNameAssignment_1.eContents().get(0);
		private final RuleCall cLPARENParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cPragmaValueAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cPragmaValuePragmaValueParserRuleCall_3_0_0 = (RuleCall)cPragmaValueAssignment_3_0.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final RuleCall cCOMMAParserRuleCall_3_1_0 = (RuleCall)cGroup_3_1.eContents().get(0);
		private final Assignment cPragmaValueAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cPragmaValuePragmaValueParserRuleCall_3_1_1_0 = (RuleCall)cPragmaValueAssignment_3_1_1.eContents().get(0);
		private final RuleCall cRPARENParserRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//pragma Pragma:
		//	PRAGMATOK pragmaName=pragmaName
		//	LPAREN (pragmaValue+=pragmaValue (COMMA pragmaValue+=pragmaValue)*)?
		//	RPAREN
		@Override public ParserRule getRule() { return rule; }
		
		//PRAGMATOK pragmaName=pragmaName LPAREN (pragmaValue+=pragmaValue (COMMA pragmaValue+=pragmaValue)*)? RPAREN
		public Group getGroup() { return cGroup; }
		
		//PRAGMATOK
		public RuleCall getPRAGMATOKParserRuleCall_0() { return cPRAGMATOKParserRuleCall_0; }
		
		//pragmaName=pragmaName
		public Assignment getPragmaNameAssignment_1() { return cPragmaNameAssignment_1; }
		
		//pragmaName
		public RuleCall getPragmaNamePragmaNameParserRuleCall_1_0() { return cPragmaNamePragmaNameParserRuleCall_1_0; }
		
		//LPAREN
		public RuleCall getLPARENParserRuleCall_2() { return cLPARENParserRuleCall_2; }
		
		//(pragmaValue+=pragmaValue (COMMA pragmaValue+=pragmaValue)*)?
		public Group getGroup_3() { return cGroup_3; }
		
		//pragmaValue+=pragmaValue
		public Assignment getPragmaValueAssignment_3_0() { return cPragmaValueAssignment_3_0; }
		
		//pragmaValue
		public RuleCall getPragmaValuePragmaValueParserRuleCall_3_0_0() { return cPragmaValuePragmaValueParserRuleCall_3_0_0; }
		
		//(COMMA pragmaValue+=pragmaValue)*
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//COMMA
		public RuleCall getCOMMAParserRuleCall_3_1_0() { return cCOMMAParserRuleCall_3_1_0; }
		
		//pragmaValue+=pragmaValue
		public Assignment getPragmaValueAssignment_3_1_1() { return cPragmaValueAssignment_3_1_1; }
		
		//pragmaValue
		public RuleCall getPragmaValuePragmaValueParserRuleCall_3_1_1_0() { return cPragmaValuePragmaValueParserRuleCall_3_1_1_0; }
		
		//RPAREN
		public RuleCall getRPARENParserRuleCall_4() { return cRPARENParserRuleCall_4; }
	}
	public class PragmaValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.pragmaValue");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLiteralParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//pragmaValue:
		//	literal
		//	| ID;
		@Override public ParserRule getRule() { return rule; }
		
		//literal | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//literal
		public RuleCall getLiteralParserRuleCall_0() { return cLiteralParserRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class PragmaNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.pragmaName");
		private final Assignment cIdentifierAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cIdentifierIDTerminalRuleCall_0 = (RuleCall)cIdentifierAssignment.eContents().get(0);
		
		//pragmaName PragmaName:
		//	identifier=ID
		@Override public ParserRule getRule() { return rule; }
		
		//identifier=ID
		public Assignment getIdentifierAssignment() { return cIdentifierAssignment; }
		
		//ID
		public RuleCall getIdentifierIDTerminalRuleCall_0() { return cIdentifierIDTerminalRuleCall_0; }
	}
	public class LiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.literal");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSTRINGTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//literal:
		//	INT
		//	| STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//INT | STRING
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_1() { return cSTRINGTerminalRuleCall_1; }
	}
	public class ANONYMOUSElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.ANONYMOUS");
		private final Keyword cAnonymousKeyword = (Keyword)rule.eContents().get(1);
		
		//// Keywords
		//ANONYMOUS:
		//	'anonymous';
		@Override public ParserRule getRule() { return rule; }
		
		//'anonymous'
		public Keyword getAnonymousKeyword() { return cAnonymousKeyword; }
	}
	public class COLONElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.COLON");
		private final Keyword cColonKeyword = (Keyword)rule.eContents().get(1);
		
		//COLON:
		//	':';
		@Override public ParserRule getRule() { return rule; }
		
		//':'
		public Keyword getColonKeyword() { return cColonKeyword; }
	}
	public class COMMAElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.COMMA");
		private final Keyword cCommaKeyword = (Keyword)rule.eContents().get(1);
		
		//COMMA:
		//	',';
		@Override public ParserRule getRule() { return rule; }
		
		//','
		public Keyword getCommaKeyword() { return cCommaKeyword; }
	}
	public class DOMAINElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.DOMAIN");
		private final Keyword cDomainKeyword = (Keyword)rule.eContents().get(1);
		
		//DOMAIN:
		//	'domain';
		@Override public ParserRule getRule() { return rule; }
		
		//'domain'
		public Keyword getDomainKeyword() { return cDomainKeyword; }
	}
	public class ENDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.END");
		private final Keyword cEndKeyword = (Keyword)rule.eContents().get(1);
		
		//END:
		//	'end';
		@Override public ParserRule getRule() { return rule; }
		
		//'end'
		public Keyword getEndKeyword() { return cEndKeyword; }
	}
	public class EVENTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.EVENT");
		private final Keyword cEventKeyword = (Keyword)rule.eContents().get(1);
		
		//EVENT:
		//	'event';
		@Override public ParserRule getRule() { return rule; }
		
		//'event'
		public Keyword getEventKeyword() { return cEventKeyword; }
	}
	public class FUNCTIONElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.FUNCTION");
		private final Keyword cFunctionKeyword = (Keyword)rule.eContents().get(1);
		
		//FUNCTION:
		//	'function';
		@Override public ParserRule getRule() { return rule; }
		
		//'function'
		public Keyword getFunctionKeyword() { return cFunctionKeyword; }
	}
	public class INElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.IN");
		private final Keyword cInKeyword = (Keyword)rule.eContents().get(1);
		
		//IN:
		//	'in';
		@Override public ParserRule getRule() { return rule; }
		
		//'in'
		public Keyword getInKeyword() { return cInKeyword; }
	}
	public class INSTANCEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.INSTANCE");
		private final Keyword cInstanceKeyword = (Keyword)rule.eContents().get(1);
		
		//INSTANCE:
		//	'instance';
		@Override public ParserRule getRule() { return rule; }
		
		//'instance'
		public Keyword getInstanceKeyword() { return cInstanceKeyword; }
	}
	public class ISElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.IS");
		private final Keyword cIsKeyword = (Keyword)rule.eContents().get(1);
		
		//IS:
		//	'is';
		@Override public ParserRule getRule() { return rule; }
		
		//'is'
		public Keyword getIsKeyword() { return cIsKeyword; }
	}
	public class LPARENElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.LPAREN");
		private final Keyword cLeftParenthesisKeyword = (Keyword)rule.eContents().get(1);
		
		//LPAREN:
		//	'(';
		@Override public ParserRule getRule() { return rule; }
		
		//'('
		public Keyword getLeftParenthesisKeyword() { return cLeftParenthesisKeyword; }
	}
	public class OFElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.OF");
		private final Keyword cOfKeyword = (Keyword)rule.eContents().get(1);
		
		//OF:
		//	'of';
		@Override public ParserRule getRule() { return rule; }
		
		//'of'
		public Keyword getOfKeyword() { return cOfKeyword; }
	}
	public class OUTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.OUT");
		private final Keyword cOutKeyword = (Keyword)rule.eContents().get(1);
		
		//OUT:
		//	'out';
		@Override public ParserRule getRule() { return rule; }
		
		//'out'
		public Keyword getOutKeyword() { return cOutKeyword; }
	}
	public class PRAGMATOKElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.PRAGMATOK");
		private final Keyword cPragmaKeyword = (Keyword)rule.eContents().get(1);
		
		//PRAGMATOK:
		//	'pragma';
		@Override public ParserRule getRule() { return rule; }
		
		//'pragma'
		public Keyword getPragmaKeyword() { return cPragmaKeyword; }
	}
	public class PRIVATEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.PRIVATE");
		private final Keyword cPrivateKeyword = (Keyword)rule.eContents().get(1);
		
		//PRIVATE:
		//	'private';
		@Override public ParserRule getRule() { return rule; }
		
		//'private'
		public Keyword getPrivateKeyword() { return cPrivateKeyword; }
	}
	public class PROJECTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.PROJECT");
		private final Keyword cProjectKeyword = (Keyword)rule.eContents().get(1);
		
		//PROJECT:
		//	'project';
		@Override public ParserRule getRule() { return rule; }
		
		//'project'
		public Keyword getProjectKeyword() { return cProjectKeyword; }
	}
	public class PUBLICElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.PUBLIC");
		private final Keyword cPublicKeyword = (Keyword)rule.eContents().get(1);
		
		//PUBLIC:
		//	'public';
		@Override public ParserRule getRule() { return rule; }
		
		//'public'
		public Keyword getPublicKeyword() { return cPublicKeyword; }
	}
	public class RETURNElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.RETURN");
		private final Keyword cReturnKeyword = (Keyword)rule.eContents().get(1);
		
		//RETURN:
		//	'return';
		@Override public ParserRule getRule() { return rule; }
		
		//'return'
		public Keyword getReturnKeyword() { return cReturnKeyword; }
	}
	public class RPARENElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.RPAREN");
		private final Keyword cRightParenthesisKeyword = (Keyword)rule.eContents().get(1);
		
		//RPAREN:
		//	')';
		@Override public ParserRule getRule() { return rule; }
		
		//')'
		public Keyword getRightParenthesisKeyword() { return cRightParenthesisKeyword; }
	}
	public class SCOPEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.SCOPE");
		private final Keyword cColonColonKeyword = (Keyword)rule.eContents().get(1);
		
		//SCOPE:
		//	'::';
		@Override public ParserRule getRule() { return rule; }
		
		//'::'
		public Keyword getColonColonKeyword() { return cColonColonKeyword; }
	}
	public class SEMIElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.SEMI");
		private final Keyword cSemicolonKeyword = (Keyword)rule.eContents().get(1);
		
		//SEMI:
		//	';';
		@Override public ParserRule getRule() { return rule; }
		
		//';'
		public Keyword getSemicolonKeyword() { return cSemicolonKeyword; }
	}
	public class SERVICEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.SERVICE");
		private final Keyword cServiceKeyword = (Keyword)rule.eContents().get(1);
		
		//SERVICE:
		//	'service';
		@Override public ParserRule getRule() { return rule; }
		
		//'service'
		public Keyword getServiceKeyword() { return cServiceKeyword; }
	}
	public class TERMINATORElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.TERMINATOR");
		private final Keyword cTerminatorKeyword = (Keyword)rule.eContents().get(1);
		
		//TERMINATOR:
		//	'terminator';
		@Override public ParserRule getRule() { return rule; }
		
		//'terminator'
		public Keyword getTerminatorKeyword() { return cTerminatorKeyword; }
	}
	public class TYPEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.bp.xtext.Masl.TYPE");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTypeKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cSubtypeKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//TYPE:
		//	'type' | 'subtype';
		@Override public ParserRule getRule() { return rule; }
		
		//'type' | 'subtype'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'type'
		public Keyword getTypeKeyword_0() { return cTypeKeyword_0; }
		
		//'subtype'
		public Keyword getSubtypeKeyword_1() { return cSubtypeKeyword_1; }
	}
	
	
	private final ProjectDefinitionElements pProjectDefinition;
	private final ProjectItemElements pProjectItem;
	private final DomainPrjDefinitionElements pDomainPrjDefinition;
	private final DomainPrjItemElements pDomainPrjItem;
	private final ProjectNameElements pProjectName;
	private final DomainNameElements pDomainName;
	private final TerminatorNameElements pTerminatorName;
	private final TerminatorDefinitionElements pTerminatorDefinition;
	private final TerminatorItemElements pTerminatorItem;
	private final TerminatorServiceDeclarationElements pTerminatorServiceDeclaration;
	private final TerminatorFunctionDeclarationElements pTerminatorFunctionDeclaration;
	private final ParameterListElements pParameterList;
	private final ParameterDefinitionElements pParameterDefinition;
	private final ServiceVisibilityElements pServiceVisibility;
	private final ParameterModeElements pParameterMode;
	private final ServiceNameElements pServiceName;
	private final ParameterNameElements pParameterName;
	private final ParameterTypeElements pParameterType;
	private final ReturnTypeElements pReturnType;
	private final TypeReferenceElements pTypeReference;
	private final DeprecatedTypeElements pDeprecatedType;
	private final NamedTypeRefElements pNamedTypeRef;
	private final TypeNameElements pTypeName;
	private final PragmaListElements pPragmaList;
	private final PragmaElements pPragma;
	private final PragmaValueElements pPragmaValue;
	private final PragmaNameElements pPragmaName;
	private final LiteralElements pLiteral;
	private final ANONYMOUSElements pANONYMOUS;
	private final COLONElements pCOLON;
	private final COMMAElements pCOMMA;
	private final DOMAINElements pDOMAIN;
	private final ENDElements pEND;
	private final EVENTElements pEVENT;
	private final FUNCTIONElements pFUNCTION;
	private final INElements pIN;
	private final INSTANCEElements pINSTANCE;
	private final ISElements pIS;
	private final LPARENElements pLPAREN;
	private final OFElements pOF;
	private final OUTElements pOUT;
	private final PRAGMATOKElements pPRAGMATOK;
	private final PRIVATEElements pPRIVATE;
	private final PROJECTElements pPROJECT;
	private final PUBLICElements pPUBLIC;
	private final RETURNElements pRETURN;
	private final RPARENElements pRPAREN;
	private final SCOPEElements pSCOPE;
	private final SEMIElements pSEMI;
	private final SERVICEElements pSERVICE;
	private final TERMINATORElements pTERMINATOR;
	private final TYPEElements pTYPE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MaslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProjectDefinition = new ProjectDefinitionElements();
		this.pProjectItem = new ProjectItemElements();
		this.pDomainPrjDefinition = new DomainPrjDefinitionElements();
		this.pDomainPrjItem = new DomainPrjItemElements();
		this.pProjectName = new ProjectNameElements();
		this.pDomainName = new DomainNameElements();
		this.pTerminatorName = new TerminatorNameElements();
		this.pTerminatorDefinition = new TerminatorDefinitionElements();
		this.pTerminatorItem = new TerminatorItemElements();
		this.pTerminatorServiceDeclaration = new TerminatorServiceDeclarationElements();
		this.pTerminatorFunctionDeclaration = new TerminatorFunctionDeclarationElements();
		this.pParameterList = new ParameterListElements();
		this.pParameterDefinition = new ParameterDefinitionElements();
		this.pServiceVisibility = new ServiceVisibilityElements();
		this.pParameterMode = new ParameterModeElements();
		this.pServiceName = new ServiceNameElements();
		this.pParameterName = new ParameterNameElements();
		this.pParameterType = new ParameterTypeElements();
		this.pReturnType = new ReturnTypeElements();
		this.pTypeReference = new TypeReferenceElements();
		this.pDeprecatedType = new DeprecatedTypeElements();
		this.pNamedTypeRef = new NamedTypeRefElements();
		this.pTypeName = new TypeNameElements();
		this.pPragmaList = new PragmaListElements();
		this.pPragma = new PragmaElements();
		this.pPragmaValue = new PragmaValueElements();
		this.pPragmaName = new PragmaNameElements();
		this.pLiteral = new LiteralElements();
		this.pANONYMOUS = new ANONYMOUSElements();
		this.pCOLON = new COLONElements();
		this.pCOMMA = new COMMAElements();
		this.pDOMAIN = new DOMAINElements();
		this.pEND = new ENDElements();
		this.pEVENT = new EVENTElements();
		this.pFUNCTION = new FUNCTIONElements();
		this.pIN = new INElements();
		this.pINSTANCE = new INSTANCEElements();
		this.pIS = new ISElements();
		this.pLPAREN = new LPARENElements();
		this.pOF = new OFElements();
		this.pOUT = new OUTElements();
		this.pPRAGMATOK = new PRAGMATOKElements();
		this.pPRIVATE = new PRIVATEElements();
		this.pPROJECT = new PROJECTElements();
		this.pPUBLIC = new PUBLICElements();
		this.pRETURN = new RETURNElements();
		this.pRPAREN = new RPARENElements();
		this.pSCOPE = new SCOPEElements();
		this.pSEMI = new SEMIElements();
		this.pSERVICE = new SERVICEElements();
		this.pTERMINATOR = new TERMINATORElements();
		this.pTYPE = new TYPEElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtuml.bp.xtext.Masl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	////target                        : projectDefinition+;
	////---------------------------------------------------------
	//// Project Definition
	////---------------------------------------------------------
	//projectDefinition Project:
	//	PROJECT projectName=projectName IS
	//	projectItem+=projectItem*
	//	END PROJECT? SEMI pragmaList=pragmaList
	public ProjectDefinitionElements getProjectDefinitionAccess() {
		return pProjectDefinition;
	}
	
	public ParserRule getProjectDefinitionRule() {
		return getProjectDefinitionAccess().getRule();
	}
	
	//projectItem:
	//	domainPrjDefinition;
	public ProjectItemElements getProjectItemAccess() {
		return pProjectItem;
	}
	
	public ParserRule getProjectItemRule() {
		return getProjectItemAccess().getRule();
	}
	
	//domainPrjDefinition Domain:
	//	DOMAIN domainName=domainName IS
	//	domainPrjItem+=domainPrjItem*
	//	END DOMAIN? SEMI pragmaList=pragmaList
	public DomainPrjDefinitionElements getDomainPrjDefinitionAccess() {
		return pDomainPrjDefinition;
	}
	
	public ParserRule getDomainPrjDefinitionRule() {
		return getDomainPrjDefinitionAccess().getRule();
	}
	
	//domainPrjItem:
	//	terminatorDefinition;
	public DomainPrjItemElements getDomainPrjItemAccess() {
		return pDomainPrjItem;
	}
	
	public ParserRule getDomainPrjItemRule() {
		return getDomainPrjItemAccess().getRule();
	}
	
	//projectName ProjectName:
	//	identifier=ID
	public ProjectNameElements getProjectNameAccess() {
		return pProjectName;
	}
	
	public ParserRule getProjectNameRule() {
		return getProjectNameAccess().getRule();
	}
	
	//domainName DomainName:
	//	identifier=ID
	public DomainNameElements getDomainNameAccess() {
		return pDomainName;
	}
	
	public ParserRule getDomainNameRule() {
		return getDomainNameAccess().getRule();
	}
	
	////---------------------------------------------------------
	//// Terminator Definition
	////---------------------------------------------------------
	//terminatorName TerminatorName:
	//	identifier=ID
	public TerminatorNameElements getTerminatorNameAccess() {
		return pTerminatorName;
	}
	
	public ParserRule getTerminatorNameRule() {
		return getTerminatorNameAccess().getRule();
	}
	
	//terminatorDefinition TerminatorDefinition:
	//	TERMINATOR terminatorName=terminatorName IS
	//	terminatorItem+=terminatorItem*
	//	END TERMINATOR? SEMI pragmaList=pragmaList
	public TerminatorDefinitionElements getTerminatorDefinitionAccess() {
		return pTerminatorDefinition;
	}
	
	public ParserRule getTerminatorDefinitionRule() {
		return getTerminatorDefinitionAccess().getRule();
	}
	
	//terminatorItem:
	//	terminatorServiceDeclaration
	//	| terminatorFunctionDeclaration;
	public TerminatorItemElements getTerminatorItemAccess() {
		return pTerminatorItem;
	}
	
	public ParserRule getTerminatorItemRule() {
		return getTerminatorItemAccess().getRule();
	}
	
	//terminatorServiceDeclaration TerminatorServiceDeclaration:
	//	serviceVisibility=serviceVisibility SERVICE serviceName=serviceName
	//	parameterList=parameterList SEMI pragmaList=pragmaList
	public TerminatorServiceDeclarationElements getTerminatorServiceDeclarationAccess() {
		return pTerminatorServiceDeclaration;
	}
	
	public ParserRule getTerminatorServiceDeclarationRule() {
		return getTerminatorServiceDeclarationAccess().getRule();
	}
	
	//terminatorFunctionDeclaration TerminatorFunctionDeclaration:
	//	serviceVisibility=serviceVisibility FUNCTION serviceName=serviceName
	//	parameterList=parameterList RETURN returnType=returnType
	//	SEMI pragmaList=pragmaList
	public TerminatorFunctionDeclarationElements getTerminatorFunctionDeclarationAccess() {
		return pTerminatorFunctionDeclaration;
	}
	
	public ParserRule getTerminatorFunctionDeclarationRule() {
		return getTerminatorFunctionDeclarationAccess().getRule();
	}
	
	//parameterList:
	//	LPAREN
	//	parameterDefinition+=parameterDefinition? (COMMA parameterDefinition+=parameterDefinition)*
	//	RPAREN;
	public ParameterListElements getParameterListAccess() {
		return pParameterList;
	}
	
	public ParserRule getParameterListRule() {
		return getParameterListAccess().getRule();
	}
	
	//parameterDefinition ParameterDefinition:
	//	parameterName=parameterName COLON parameterMode=parameterMode parameterType=parameterType
	public ParameterDefinitionElements getParameterDefinitionAccess() {
		return pParameterDefinition;
	}
	
	public ParserRule getParameterDefinitionRule() {
		return getParameterDefinitionAccess().getRule();
	}
	
	/// * fix for blank * / serviceVisibility:
	//	PRIVATE
	//	| PUBLIC;
	public ServiceVisibilityElements getServiceVisibilityAccess() {
		return pServiceVisibility;
	}
	
	public ParserRule getServiceVisibilityRule() {
		return getServiceVisibilityAccess().getRule();
	}
	
	//parameterMode:
	//	IN
	//	| OUT;
	public ParameterModeElements getParameterModeAccess() {
		return pParameterMode;
	}
	
	public ParserRule getParameterModeRule() {
		return getParameterModeAccess().getRule();
	}
	
	//serviceName ServiceName:
	//	identifier=ID
	public ServiceNameElements getServiceNameAccess() {
		return pServiceName;
	}
	
	public ParserRule getServiceNameRule() {
		return getServiceNameAccess().getRule();
	}
	
	//parameterName ParameterName:
	//	identifier=ID
	public ParameterNameElements getParameterNameAccess() {
		return pParameterName;
	}
	
	public ParserRule getParameterNameRule() {
		return getParameterNameAccess().getRule();
	}
	
	//parameterType ParameterType:
	//	typeReference=typeReference
	public ParameterTypeElements getParameterTypeAccess() {
		return pParameterType;
	}
	
	public ParserRule getParameterTypeRule() {
		return getParameterTypeAccess().getRule();
	}
	
	//returnType ReturnType:
	//	typeReference=typeReference
	public ReturnTypeElements getReturnTypeAccess() {
		return pReturnType;
	}
	
	public ParserRule getReturnTypeRule() {
		return getReturnTypeAccess().getRule();
	}
	
	////---------------------------------------------------------
	//// Type Reference
	////---------------------------------------------------------
	//typeReference:
	//	namedTypeRef
	//	| deprecatedType;
	public TypeReferenceElements getTypeReferenceAccess() {
		return pTypeReference;
	}
	
	public ParserRule getTypeReferenceRule() {
		return getTypeReferenceAccess().getRule();
	}
	
	//deprecatedType:
	//	INSTANCE
	//	| EVENT
	//	| SERVICE;
	public DeprecatedTypeElements getDeprecatedTypeAccess() {
		return pDeprecatedType;
	}
	
	public ParserRule getDeprecatedTypeRule() {
		return getDeprecatedTypeAccess().getRule();
	}
	
	//namedTypeRef NamedType:
	//	anonymous=ANONYMOUS? (domainName=domainName SCOPE)? typeName=typeName
	public NamedTypeRefElements getNamedTypeRefAccess() {
		return pNamedTypeRef;
	}
	
	public ParserRule getNamedTypeRefRule() {
		return getNamedTypeRefAccess().getRule();
	}
	
	//typeName TypeName:
	//	identifier=ID
	public TypeNameElements getTypeNameAccess() {
		return pTypeName;
	}
	
	public ParserRule getTypeNameRule() {
		return getTypeNameAccess().getRule();
	}
	
	////---------------------------------------------------------
	//// Pragma Definition
	////---------------------------------------------------------
	//pragmaList PragmaList:
	//	(pragma+=pragma SEMI)*
	public PragmaListElements getPragmaListAccess() {
		return pPragmaList;
	}
	
	public ParserRule getPragmaListRule() {
		return getPragmaListAccess().getRule();
	}
	
	//pragma Pragma:
	//	PRAGMATOK pragmaName=pragmaName
	//	LPAREN (pragmaValue+=pragmaValue (COMMA pragmaValue+=pragmaValue)*)?
	//	RPAREN
	public PragmaElements getPragmaAccess() {
		return pPragma;
	}
	
	public ParserRule getPragmaRule() {
		return getPragmaAccess().getRule();
	}
	
	//pragmaValue:
	//	literal
	//	| ID;
	public PragmaValueElements getPragmaValueAccess() {
		return pPragmaValue;
	}
	
	public ParserRule getPragmaValueRule() {
		return getPragmaValueAccess().getRule();
	}
	
	//pragmaName PragmaName:
	//	identifier=ID
	public PragmaNameElements getPragmaNameAccess() {
		return pPragmaName;
	}
	
	public ParserRule getPragmaNameRule() {
		return getPragmaNameAccess().getRule();
	}
	
	//literal:
	//	INT
	//	| STRING;
	public LiteralElements getLiteralAccess() {
		return pLiteral;
	}
	
	public ParserRule getLiteralRule() {
		return getLiteralAccess().getRule();
	}
	
	//// Keywords
	//ANONYMOUS:
	//	'anonymous';
	public ANONYMOUSElements getANONYMOUSAccess() {
		return pANONYMOUS;
	}
	
	public ParserRule getANONYMOUSRule() {
		return getANONYMOUSAccess().getRule();
	}
	
	//COLON:
	//	':';
	public COLONElements getCOLONAccess() {
		return pCOLON;
	}
	
	public ParserRule getCOLONRule() {
		return getCOLONAccess().getRule();
	}
	
	//COMMA:
	//	',';
	public COMMAElements getCOMMAAccess() {
		return pCOMMA;
	}
	
	public ParserRule getCOMMARule() {
		return getCOMMAAccess().getRule();
	}
	
	//DOMAIN:
	//	'domain';
	public DOMAINElements getDOMAINAccess() {
		return pDOMAIN;
	}
	
	public ParserRule getDOMAINRule() {
		return getDOMAINAccess().getRule();
	}
	
	//END:
	//	'end';
	public ENDElements getENDAccess() {
		return pEND;
	}
	
	public ParserRule getENDRule() {
		return getENDAccess().getRule();
	}
	
	//EVENT:
	//	'event';
	public EVENTElements getEVENTAccess() {
		return pEVENT;
	}
	
	public ParserRule getEVENTRule() {
		return getEVENTAccess().getRule();
	}
	
	//FUNCTION:
	//	'function';
	public FUNCTIONElements getFUNCTIONAccess() {
		return pFUNCTION;
	}
	
	public ParserRule getFUNCTIONRule() {
		return getFUNCTIONAccess().getRule();
	}
	
	//IN:
	//	'in';
	public INElements getINAccess() {
		return pIN;
	}
	
	public ParserRule getINRule() {
		return getINAccess().getRule();
	}
	
	//INSTANCE:
	//	'instance';
	public INSTANCEElements getINSTANCEAccess() {
		return pINSTANCE;
	}
	
	public ParserRule getINSTANCERule() {
		return getINSTANCEAccess().getRule();
	}
	
	//IS:
	//	'is';
	public ISElements getISAccess() {
		return pIS;
	}
	
	public ParserRule getISRule() {
		return getISAccess().getRule();
	}
	
	//LPAREN:
	//	'(';
	public LPARENElements getLPARENAccess() {
		return pLPAREN;
	}
	
	public ParserRule getLPARENRule() {
		return getLPARENAccess().getRule();
	}
	
	//OF:
	//	'of';
	public OFElements getOFAccess() {
		return pOF;
	}
	
	public ParserRule getOFRule() {
		return getOFAccess().getRule();
	}
	
	//OUT:
	//	'out';
	public OUTElements getOUTAccess() {
		return pOUT;
	}
	
	public ParserRule getOUTRule() {
		return getOUTAccess().getRule();
	}
	
	//PRAGMATOK:
	//	'pragma';
	public PRAGMATOKElements getPRAGMATOKAccess() {
		return pPRAGMATOK;
	}
	
	public ParserRule getPRAGMATOKRule() {
		return getPRAGMATOKAccess().getRule();
	}
	
	//PRIVATE:
	//	'private';
	public PRIVATEElements getPRIVATEAccess() {
		return pPRIVATE;
	}
	
	public ParserRule getPRIVATERule() {
		return getPRIVATEAccess().getRule();
	}
	
	//PROJECT:
	//	'project';
	public PROJECTElements getPROJECTAccess() {
		return pPROJECT;
	}
	
	public ParserRule getPROJECTRule() {
		return getPROJECTAccess().getRule();
	}
	
	//PUBLIC:
	//	'public';
	public PUBLICElements getPUBLICAccess() {
		return pPUBLIC;
	}
	
	public ParserRule getPUBLICRule() {
		return getPUBLICAccess().getRule();
	}
	
	//RETURN:
	//	'return';
	public RETURNElements getRETURNAccess() {
		return pRETURN;
	}
	
	public ParserRule getRETURNRule() {
		return getRETURNAccess().getRule();
	}
	
	//RPAREN:
	//	')';
	public RPARENElements getRPARENAccess() {
		return pRPAREN;
	}
	
	public ParserRule getRPARENRule() {
		return getRPARENAccess().getRule();
	}
	
	//SCOPE:
	//	'::';
	public SCOPEElements getSCOPEAccess() {
		return pSCOPE;
	}
	
	public ParserRule getSCOPERule() {
		return getSCOPEAccess().getRule();
	}
	
	//SEMI:
	//	';';
	public SEMIElements getSEMIAccess() {
		return pSEMI;
	}
	
	public ParserRule getSEMIRule() {
		return getSEMIAccess().getRule();
	}
	
	//SERVICE:
	//	'service';
	public SERVICEElements getSERVICEAccess() {
		return pSERVICE;
	}
	
	public ParserRule getSERVICERule() {
		return getSERVICEAccess().getRule();
	}
	
	//TERMINATOR:
	//	'terminator';
	public TERMINATORElements getTERMINATORAccess() {
		return pTERMINATOR;
	}
	
	public ParserRule getTERMINATORRule() {
		return getTERMINATORAccess().getRule();
	}
	
	//TYPE:
	//	'type' | 'subtype';
	public TYPEElements getTYPEAccess() {
		return pTYPE;
	}
	
	public ParserRule getTYPERule() {
		return getTYPEAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
