/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.masl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtuml.bp.xtext.masl.MaslPackage;
import org.xtuml.bp.xtext.masl.domainPrjItem;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>domain Prj Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class domainPrjItemImpl extends MinimalEObjectImpl.Container implements domainPrjItem
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected domainPrjItemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MaslPackage.Literals.DOMAIN_PRJ_ITEM;
  }

} //domainPrjItemImpl
