/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.masl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtuml.bp.xtext.masl.CodeBlock;
import org.xtuml.bp.xtext.masl.DomainName;
import org.xtuml.bp.xtext.masl.MaslPackage;
import org.xtuml.bp.xtext.masl.ObjectName;
import org.xtuml.bp.xtext.masl.ObjectServiceDefinition;
import org.xtuml.bp.xtext.masl.PragmaList;
import org.xtuml.bp.xtext.masl.ReturnType;
import org.xtuml.bp.xtext.masl.ServiceName;
import org.xtuml.bp.xtext.masl.parameterList;
import org.xtuml.bp.xtext.masl.serviceType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Object Service Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.ObjectServiceDefinitionImpl#getServiceVisibility <em>Service Visibility</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.ObjectServiceDefinitionImpl#getINSTANCE <em>INSTANCE</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.ObjectServiceDefinitionImpl#getDomainName <em>Domain Name</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.ObjectServiceDefinitionImpl#getObjectName <em>Object Name</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.ObjectServiceDefinitionImpl#getServiceName <em>Service Name</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.ObjectServiceDefinitionImpl#getParameterList <em>Parameter List</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.ObjectServiceDefinitionImpl#getCodeBlock <em>Code Block</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.ObjectServiceDefinitionImpl#getPragmaList <em>Pragma List</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.ObjectServiceDefinitionImpl#getServiceType <em>Service Type</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.ObjectServiceDefinitionImpl#getReturnType <em>Return Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ObjectServiceDefinitionImpl extends definitionImpl implements ObjectServiceDefinition
{
  /**
   * The default value of the '{@link #getServiceVisibility() <em>Service Visibility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getServiceVisibility()
   * @generated
   * @ordered
   */
  protected static final String SERVICE_VISIBILITY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getServiceVisibility() <em>Service Visibility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getServiceVisibility()
   * @generated
   * @ordered
   */
  protected String serviceVisibility = SERVICE_VISIBILITY_EDEFAULT;

  /**
   * The default value of the '{@link #getINSTANCE() <em>INSTANCE</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getINSTANCE()
   * @generated
   * @ordered
   */
  protected static final String INSTANCE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getINSTANCE() <em>INSTANCE</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getINSTANCE()
   * @generated
   * @ordered
   */
  protected String instance = INSTANCE_EDEFAULT;

  /**
   * The cached value of the '{@link #getDomainName() <em>Domain Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDomainName()
   * @generated
   * @ordered
   */
  protected DomainName domainName;

  /**
   * The cached value of the '{@link #getObjectName() <em>Object Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjectName()
   * @generated
   * @ordered
   */
  protected ObjectName objectName;

  /**
   * The cached value of the '{@link #getServiceName() <em>Service Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getServiceName()
   * @generated
   * @ordered
   */
  protected ServiceName serviceName;

  /**
   * The cached value of the '{@link #getParameterList() <em>Parameter List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameterList()
   * @generated
   * @ordered
   */
  protected parameterList parameterList;

  /**
   * The cached value of the '{@link #getCodeBlock() <em>Code Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeBlock()
   * @generated
   * @ordered
   */
  protected CodeBlock codeBlock;

  /**
   * The cached value of the '{@link #getPragmaList() <em>Pragma List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPragmaList()
   * @generated
   * @ordered
   */
  protected PragmaList pragmaList;

  /**
   * The cached value of the '{@link #getServiceType() <em>Service Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getServiceType()
   * @generated
   * @ordered
   */
  protected serviceType serviceType;

  /**
   * The cached value of the '{@link #getReturnType() <em>Return Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReturnType()
   * @generated
   * @ordered
   */
  protected ReturnType returnType;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ObjectServiceDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MaslPackage.Literals.OBJECT_SERVICE_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getServiceVisibility()
  {
    return serviceVisibility;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setServiceVisibility(String newServiceVisibility)
  {
    String oldServiceVisibility = serviceVisibility;
    serviceVisibility = newServiceVisibility;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_VISIBILITY, oldServiceVisibility, serviceVisibility));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getINSTANCE()
  {
    return instance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setINSTANCE(String newINSTANCE)
  {
    String oldINSTANCE = instance;
    instance = newINSTANCE;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__INSTANCE, oldINSTANCE, instance));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DomainName getDomainName()
  {
    return domainName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDomainName(DomainName newDomainName, NotificationChain msgs)
  {
    DomainName oldDomainName = domainName;
    domainName = newDomainName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__DOMAIN_NAME, oldDomainName, newDomainName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDomainName(DomainName newDomainName)
  {
    if (newDomainName != domainName)
    {
      NotificationChain msgs = null;
      if (domainName != null)
        msgs = ((InternalEObject)domainName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MaslPackage.OBJECT_SERVICE_DEFINITION__DOMAIN_NAME, null, msgs);
      if (newDomainName != null)
        msgs = ((InternalEObject)newDomainName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MaslPackage.OBJECT_SERVICE_DEFINITION__DOMAIN_NAME, null, msgs);
      msgs = basicSetDomainName(newDomainName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__DOMAIN_NAME, newDomainName, newDomainName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ObjectName getObjectName()
  {
    return objectName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetObjectName(ObjectName newObjectName, NotificationChain msgs)
  {
    ObjectName oldObjectName = objectName;
    objectName = newObjectName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__OBJECT_NAME, oldObjectName, newObjectName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setObjectName(ObjectName newObjectName)
  {
    if (newObjectName != objectName)
    {
      NotificationChain msgs = null;
      if (objectName != null)
        msgs = ((InternalEObject)objectName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MaslPackage.OBJECT_SERVICE_DEFINITION__OBJECT_NAME, null, msgs);
      if (newObjectName != null)
        msgs = ((InternalEObject)newObjectName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MaslPackage.OBJECT_SERVICE_DEFINITION__OBJECT_NAME, null, msgs);
      msgs = basicSetObjectName(newObjectName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__OBJECT_NAME, newObjectName, newObjectName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ServiceName getServiceName()
  {
    return serviceName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetServiceName(ServiceName newServiceName, NotificationChain msgs)
  {
    ServiceName oldServiceName = serviceName;
    serviceName = newServiceName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_NAME, oldServiceName, newServiceName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setServiceName(ServiceName newServiceName)
  {
    if (newServiceName != serviceName)
    {
      NotificationChain msgs = null;
      if (serviceName != null)
        msgs = ((InternalEObject)serviceName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_NAME, null, msgs);
      if (newServiceName != null)
        msgs = ((InternalEObject)newServiceName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_NAME, null, msgs);
      msgs = basicSetServiceName(newServiceName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_NAME, newServiceName, newServiceName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public parameterList getParameterList()
  {
    return parameterList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetParameterList(parameterList newParameterList, NotificationChain msgs)
  {
    parameterList oldParameterList = parameterList;
    parameterList = newParameterList;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__PARAMETER_LIST, oldParameterList, newParameterList);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setParameterList(parameterList newParameterList)
  {
    if (newParameterList != parameterList)
    {
      NotificationChain msgs = null;
      if (parameterList != null)
        msgs = ((InternalEObject)parameterList).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MaslPackage.OBJECT_SERVICE_DEFINITION__PARAMETER_LIST, null, msgs);
      if (newParameterList != null)
        msgs = ((InternalEObject)newParameterList).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MaslPackage.OBJECT_SERVICE_DEFINITION__PARAMETER_LIST, null, msgs);
      msgs = basicSetParameterList(newParameterList, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__PARAMETER_LIST, newParameterList, newParameterList));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CodeBlock getCodeBlock()
  {
    return codeBlock;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCodeBlock(CodeBlock newCodeBlock, NotificationChain msgs)
  {
    CodeBlock oldCodeBlock = codeBlock;
    codeBlock = newCodeBlock;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__CODE_BLOCK, oldCodeBlock, newCodeBlock);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCodeBlock(CodeBlock newCodeBlock)
  {
    if (newCodeBlock != codeBlock)
    {
      NotificationChain msgs = null;
      if (codeBlock != null)
        msgs = ((InternalEObject)codeBlock).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MaslPackage.OBJECT_SERVICE_DEFINITION__CODE_BLOCK, null, msgs);
      if (newCodeBlock != null)
        msgs = ((InternalEObject)newCodeBlock).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MaslPackage.OBJECT_SERVICE_DEFINITION__CODE_BLOCK, null, msgs);
      msgs = basicSetCodeBlock(newCodeBlock, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__CODE_BLOCK, newCodeBlock, newCodeBlock));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PragmaList getPragmaList()
  {
    return pragmaList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPragmaList(PragmaList newPragmaList, NotificationChain msgs)
  {
    PragmaList oldPragmaList = pragmaList;
    pragmaList = newPragmaList;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__PRAGMA_LIST, oldPragmaList, newPragmaList);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPragmaList(PragmaList newPragmaList)
  {
    if (newPragmaList != pragmaList)
    {
      NotificationChain msgs = null;
      if (pragmaList != null)
        msgs = ((InternalEObject)pragmaList).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MaslPackage.OBJECT_SERVICE_DEFINITION__PRAGMA_LIST, null, msgs);
      if (newPragmaList != null)
        msgs = ((InternalEObject)newPragmaList).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MaslPackage.OBJECT_SERVICE_DEFINITION__PRAGMA_LIST, null, msgs);
      msgs = basicSetPragmaList(newPragmaList, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__PRAGMA_LIST, newPragmaList, newPragmaList));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public serviceType getServiceType()
  {
    return serviceType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetServiceType(serviceType newServiceType, NotificationChain msgs)
  {
    serviceType oldServiceType = serviceType;
    serviceType = newServiceType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_TYPE, oldServiceType, newServiceType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setServiceType(serviceType newServiceType)
  {
    if (newServiceType != serviceType)
    {
      NotificationChain msgs = null;
      if (serviceType != null)
        msgs = ((InternalEObject)serviceType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_TYPE, null, msgs);
      if (newServiceType != null)
        msgs = ((InternalEObject)newServiceType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_TYPE, null, msgs);
      msgs = basicSetServiceType(newServiceType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_TYPE, newServiceType, newServiceType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ReturnType getReturnType()
  {
    return returnType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReturnType(ReturnType newReturnType, NotificationChain msgs)
  {
    ReturnType oldReturnType = returnType;
    returnType = newReturnType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__RETURN_TYPE, oldReturnType, newReturnType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setReturnType(ReturnType newReturnType)
  {
    if (newReturnType != returnType)
    {
      NotificationChain msgs = null;
      if (returnType != null)
        msgs = ((InternalEObject)returnType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MaslPackage.OBJECT_SERVICE_DEFINITION__RETURN_TYPE, null, msgs);
      if (newReturnType != null)
        msgs = ((InternalEObject)newReturnType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MaslPackage.OBJECT_SERVICE_DEFINITION__RETURN_TYPE, null, msgs);
      msgs = basicSetReturnType(newReturnType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.OBJECT_SERVICE_DEFINITION__RETURN_TYPE, newReturnType, newReturnType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MaslPackage.OBJECT_SERVICE_DEFINITION__DOMAIN_NAME:
        return basicSetDomainName(null, msgs);
      case MaslPackage.OBJECT_SERVICE_DEFINITION__OBJECT_NAME:
        return basicSetObjectName(null, msgs);
      case MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_NAME:
        return basicSetServiceName(null, msgs);
      case MaslPackage.OBJECT_SERVICE_DEFINITION__PARAMETER_LIST:
        return basicSetParameterList(null, msgs);
      case MaslPackage.OBJECT_SERVICE_DEFINITION__CODE_BLOCK:
        return basicSetCodeBlock(null, msgs);
      case MaslPackage.OBJECT_SERVICE_DEFINITION__PRAGMA_LIST:
        return basicSetPragmaList(null, msgs);
      case MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_TYPE:
        return basicSetServiceType(null, msgs);
      case MaslPackage.OBJECT_SERVICE_DEFINITION__RETURN_TYPE:
        return basicSetReturnType(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_VISIBILITY:
        return getServiceVisibility();
      case MaslPackage.OBJECT_SERVICE_DEFINITION__INSTANCE:
        return getINSTANCE();
      case MaslPackage.OBJECT_SERVICE_DEFINITION__DOMAIN_NAME:
        return getDomainName();
      case MaslPackage.OBJECT_SERVICE_DEFINITION__OBJECT_NAME:
        return getObjectName();
      case MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_NAME:
        return getServiceName();
      case MaslPackage.OBJECT_SERVICE_DEFINITION__PARAMETER_LIST:
        return getParameterList();
      case MaslPackage.OBJECT_SERVICE_DEFINITION__CODE_BLOCK:
        return getCodeBlock();
      case MaslPackage.OBJECT_SERVICE_DEFINITION__PRAGMA_LIST:
        return getPragmaList();
      case MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_TYPE:
        return getServiceType();
      case MaslPackage.OBJECT_SERVICE_DEFINITION__RETURN_TYPE:
        return getReturnType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_VISIBILITY:
        setServiceVisibility((String)newValue);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__INSTANCE:
        setINSTANCE((String)newValue);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__DOMAIN_NAME:
        setDomainName((DomainName)newValue);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__OBJECT_NAME:
        setObjectName((ObjectName)newValue);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_NAME:
        setServiceName((ServiceName)newValue);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__PARAMETER_LIST:
        setParameterList((parameterList)newValue);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__CODE_BLOCK:
        setCodeBlock((CodeBlock)newValue);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__PRAGMA_LIST:
        setPragmaList((PragmaList)newValue);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_TYPE:
        setServiceType((serviceType)newValue);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__RETURN_TYPE:
        setReturnType((ReturnType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_VISIBILITY:
        setServiceVisibility(SERVICE_VISIBILITY_EDEFAULT);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__INSTANCE:
        setINSTANCE(INSTANCE_EDEFAULT);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__DOMAIN_NAME:
        setDomainName((DomainName)null);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__OBJECT_NAME:
        setObjectName((ObjectName)null);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_NAME:
        setServiceName((ServiceName)null);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__PARAMETER_LIST:
        setParameterList((parameterList)null);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__CODE_BLOCK:
        setCodeBlock((CodeBlock)null);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__PRAGMA_LIST:
        setPragmaList((PragmaList)null);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_TYPE:
        setServiceType((serviceType)null);
        return;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__RETURN_TYPE:
        setReturnType((ReturnType)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_VISIBILITY:
        return SERVICE_VISIBILITY_EDEFAULT == null ? serviceVisibility != null : !SERVICE_VISIBILITY_EDEFAULT.equals(serviceVisibility);
      case MaslPackage.OBJECT_SERVICE_DEFINITION__INSTANCE:
        return INSTANCE_EDEFAULT == null ? instance != null : !INSTANCE_EDEFAULT.equals(instance);
      case MaslPackage.OBJECT_SERVICE_DEFINITION__DOMAIN_NAME:
        return domainName != null;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__OBJECT_NAME:
        return objectName != null;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_NAME:
        return serviceName != null;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__PARAMETER_LIST:
        return parameterList != null;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__CODE_BLOCK:
        return codeBlock != null;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__PRAGMA_LIST:
        return pragmaList != null;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__SERVICE_TYPE:
        return serviceType != null;
      case MaslPackage.OBJECT_SERVICE_DEFINITION__RETURN_TYPE:
        return returnType != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (serviceVisibility: ");
    result.append(serviceVisibility);
    result.append(", INSTANCE: ");
    result.append(instance);
    result.append(')');
    return result.toString();
  }

} //ObjectServiceDefinitionImpl
