/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.masl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtuml.bp.xtext.masl.MaslPackage;
import org.xtuml.bp.xtext.masl.projectItem;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>project Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class projectItemImpl extends MinimalEObjectImpl.Container implements projectItem
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected projectItemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MaslPackage.Literals.PROJECT_ITEM;
  }

} //projectItemImpl
