/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.masl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtuml.bp.xtext.masl.CodeBlock;
import org.xtuml.bp.xtext.masl.DomainName;
import org.xtuml.bp.xtext.masl.MaslPackage;
import org.xtuml.bp.xtext.masl.PragmaList;
import org.xtuml.bp.xtext.masl.ReturnType;
import org.xtuml.bp.xtext.masl.ServiceName;
import org.xtuml.bp.xtext.masl.TerminatorName;
import org.xtuml.bp.xtext.masl.TerminatorServiceDefinition;
import org.xtuml.bp.xtext.masl.parameterList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Terminator Service Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.TerminatorServiceDefinitionImpl#getServiceVisibility <em>Service Visibility</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.TerminatorServiceDefinitionImpl#getDomainName <em>Domain Name</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.TerminatorServiceDefinitionImpl#getTerminatorName <em>Terminator Name</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.TerminatorServiceDefinitionImpl#getServiceName <em>Service Name</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.TerminatorServiceDefinitionImpl#getParameterList <em>Parameter List</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.TerminatorServiceDefinitionImpl#getCodeBlock <em>Code Block</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.TerminatorServiceDefinitionImpl#getPragmaList <em>Pragma List</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.impl.TerminatorServiceDefinitionImpl#getReturnType <em>Return Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TerminatorServiceDefinitionImpl extends definitionImpl implements TerminatorServiceDefinition
{
  /**
   * The default value of the '{@link #getServiceVisibility() <em>Service Visibility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getServiceVisibility()
   * @generated
   * @ordered
   */
  protected static final String SERVICE_VISIBILITY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getServiceVisibility() <em>Service Visibility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getServiceVisibility()
   * @generated
   * @ordered
   */
  protected String serviceVisibility = SERVICE_VISIBILITY_EDEFAULT;

  /**
   * The cached value of the '{@link #getDomainName() <em>Domain Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDomainName()
   * @generated
   * @ordered
   */
  protected DomainName domainName;

  /**
   * The cached value of the '{@link #getTerminatorName() <em>Terminator Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTerminatorName()
   * @generated
   * @ordered
   */
  protected TerminatorName terminatorName;

  /**
   * The cached value of the '{@link #getServiceName() <em>Service Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getServiceName()
   * @generated
   * @ordered
   */
  protected ServiceName serviceName;

  /**
   * The cached value of the '{@link #getParameterList() <em>Parameter List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameterList()
   * @generated
   * @ordered
   */
  protected parameterList parameterList;

  /**
   * The cached value of the '{@link #getCodeBlock() <em>Code Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeBlock()
   * @generated
   * @ordered
   */
  protected CodeBlock codeBlock;

  /**
   * The cached value of the '{@link #getPragmaList() <em>Pragma List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPragmaList()
   * @generated
   * @ordered
   */
  protected PragmaList pragmaList;

  /**
   * The cached value of the '{@link #getReturnType() <em>Return Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReturnType()
   * @generated
   * @ordered
   */
  protected ReturnType returnType;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TerminatorServiceDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MaslPackage.Literals.TERMINATOR_SERVICE_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getServiceVisibility()
  {
    return serviceVisibility;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setServiceVisibility(String newServiceVisibility)
  {
    String oldServiceVisibility = serviceVisibility;
    serviceVisibility = newServiceVisibility;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.TERMINATOR_SERVICE_DEFINITION__SERVICE_VISIBILITY, oldServiceVisibility, serviceVisibility));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DomainName getDomainName()
  {
    return domainName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDomainName(DomainName newDomainName, NotificationChain msgs)
  {
    DomainName oldDomainName = domainName;
    domainName = newDomainName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MaslPackage.TERMINATOR_SERVICE_DEFINITION__DOMAIN_NAME, oldDomainName, newDomainName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDomainName(DomainName newDomainName)
  {
    if (newDomainName != domainName)
    {
      NotificationChain msgs = null;
      if (domainName != null)
        msgs = ((InternalEObject)domainName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MaslPackage.TERMINATOR_SERVICE_DEFINITION__DOMAIN_NAME, null, msgs);
      if (newDomainName != null)
        msgs = ((InternalEObject)newDomainName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MaslPackage.TERMINATOR_SERVICE_DEFINITION__DOMAIN_NAME, null, msgs);
      msgs = basicSetDomainName(newDomainName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.TERMINATOR_SERVICE_DEFINITION__DOMAIN_NAME, newDomainName, newDomainName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TerminatorName getTerminatorName()
  {
    return terminatorName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTerminatorName(TerminatorName newTerminatorName, NotificationChain msgs)
  {
    TerminatorName oldTerminatorName = terminatorName;
    terminatorName = newTerminatorName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MaslPackage.TERMINATOR_SERVICE_DEFINITION__TERMINATOR_NAME, oldTerminatorName, newTerminatorName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTerminatorName(TerminatorName newTerminatorName)
  {
    if (newTerminatorName != terminatorName)
    {
      NotificationChain msgs = null;
      if (terminatorName != null)
        msgs = ((InternalEObject)terminatorName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MaslPackage.TERMINATOR_SERVICE_DEFINITION__TERMINATOR_NAME, null, msgs);
      if (newTerminatorName != null)
        msgs = ((InternalEObject)newTerminatorName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MaslPackage.TERMINATOR_SERVICE_DEFINITION__TERMINATOR_NAME, null, msgs);
      msgs = basicSetTerminatorName(newTerminatorName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.TERMINATOR_SERVICE_DEFINITION__TERMINATOR_NAME, newTerminatorName, newTerminatorName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ServiceName getServiceName()
  {
    return serviceName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetServiceName(ServiceName newServiceName, NotificationChain msgs)
  {
    ServiceName oldServiceName = serviceName;
    serviceName = newServiceName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MaslPackage.TERMINATOR_SERVICE_DEFINITION__SERVICE_NAME, oldServiceName, newServiceName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setServiceName(ServiceName newServiceName)
  {
    if (newServiceName != serviceName)
    {
      NotificationChain msgs = null;
      if (serviceName != null)
        msgs = ((InternalEObject)serviceName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MaslPackage.TERMINATOR_SERVICE_DEFINITION__SERVICE_NAME, null, msgs);
      if (newServiceName != null)
        msgs = ((InternalEObject)newServiceName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MaslPackage.TERMINATOR_SERVICE_DEFINITION__SERVICE_NAME, null, msgs);
      msgs = basicSetServiceName(newServiceName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.TERMINATOR_SERVICE_DEFINITION__SERVICE_NAME, newServiceName, newServiceName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public parameterList getParameterList()
  {
    return parameterList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetParameterList(parameterList newParameterList, NotificationChain msgs)
  {
    parameterList oldParameterList = parameterList;
    parameterList = newParameterList;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MaslPackage.TERMINATOR_SERVICE_DEFINITION__PARAMETER_LIST, oldParameterList, newParameterList);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setParameterList(parameterList newParameterList)
  {
    if (newParameterList != parameterList)
    {
      NotificationChain msgs = null;
      if (parameterList != null)
        msgs = ((InternalEObject)parameterList).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MaslPackage.TERMINATOR_SERVICE_DEFINITION__PARAMETER_LIST, null, msgs);
      if (newParameterList != null)
        msgs = ((InternalEObject)newParameterList).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MaslPackage.TERMINATOR_SERVICE_DEFINITION__PARAMETER_LIST, null, msgs);
      msgs = basicSetParameterList(newParameterList, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.TERMINATOR_SERVICE_DEFINITION__PARAMETER_LIST, newParameterList, newParameterList));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CodeBlock getCodeBlock()
  {
    return codeBlock;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCodeBlock(CodeBlock newCodeBlock, NotificationChain msgs)
  {
    CodeBlock oldCodeBlock = codeBlock;
    codeBlock = newCodeBlock;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MaslPackage.TERMINATOR_SERVICE_DEFINITION__CODE_BLOCK, oldCodeBlock, newCodeBlock);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCodeBlock(CodeBlock newCodeBlock)
  {
    if (newCodeBlock != codeBlock)
    {
      NotificationChain msgs = null;
      if (codeBlock != null)
        msgs = ((InternalEObject)codeBlock).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MaslPackage.TERMINATOR_SERVICE_DEFINITION__CODE_BLOCK, null, msgs);
      if (newCodeBlock != null)
        msgs = ((InternalEObject)newCodeBlock).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MaslPackage.TERMINATOR_SERVICE_DEFINITION__CODE_BLOCK, null, msgs);
      msgs = basicSetCodeBlock(newCodeBlock, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.TERMINATOR_SERVICE_DEFINITION__CODE_BLOCK, newCodeBlock, newCodeBlock));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PragmaList getPragmaList()
  {
    return pragmaList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPragmaList(PragmaList newPragmaList, NotificationChain msgs)
  {
    PragmaList oldPragmaList = pragmaList;
    pragmaList = newPragmaList;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MaslPackage.TERMINATOR_SERVICE_DEFINITION__PRAGMA_LIST, oldPragmaList, newPragmaList);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPragmaList(PragmaList newPragmaList)
  {
    if (newPragmaList != pragmaList)
    {
      NotificationChain msgs = null;
      if (pragmaList != null)
        msgs = ((InternalEObject)pragmaList).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MaslPackage.TERMINATOR_SERVICE_DEFINITION__PRAGMA_LIST, null, msgs);
      if (newPragmaList != null)
        msgs = ((InternalEObject)newPragmaList).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MaslPackage.TERMINATOR_SERVICE_DEFINITION__PRAGMA_LIST, null, msgs);
      msgs = basicSetPragmaList(newPragmaList, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.TERMINATOR_SERVICE_DEFINITION__PRAGMA_LIST, newPragmaList, newPragmaList));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ReturnType getReturnType()
  {
    return returnType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReturnType(ReturnType newReturnType, NotificationChain msgs)
  {
    ReturnType oldReturnType = returnType;
    returnType = newReturnType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MaslPackage.TERMINATOR_SERVICE_DEFINITION__RETURN_TYPE, oldReturnType, newReturnType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setReturnType(ReturnType newReturnType)
  {
    if (newReturnType != returnType)
    {
      NotificationChain msgs = null;
      if (returnType != null)
        msgs = ((InternalEObject)returnType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MaslPackage.TERMINATOR_SERVICE_DEFINITION__RETURN_TYPE, null, msgs);
      if (newReturnType != null)
        msgs = ((InternalEObject)newReturnType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MaslPackage.TERMINATOR_SERVICE_DEFINITION__RETURN_TYPE, null, msgs);
      msgs = basicSetReturnType(newReturnType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MaslPackage.TERMINATOR_SERVICE_DEFINITION__RETURN_TYPE, newReturnType, newReturnType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__DOMAIN_NAME:
        return basicSetDomainName(null, msgs);
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__TERMINATOR_NAME:
        return basicSetTerminatorName(null, msgs);
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__SERVICE_NAME:
        return basicSetServiceName(null, msgs);
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__PARAMETER_LIST:
        return basicSetParameterList(null, msgs);
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__CODE_BLOCK:
        return basicSetCodeBlock(null, msgs);
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__PRAGMA_LIST:
        return basicSetPragmaList(null, msgs);
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__RETURN_TYPE:
        return basicSetReturnType(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__SERVICE_VISIBILITY:
        return getServiceVisibility();
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__DOMAIN_NAME:
        return getDomainName();
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__TERMINATOR_NAME:
        return getTerminatorName();
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__SERVICE_NAME:
        return getServiceName();
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__PARAMETER_LIST:
        return getParameterList();
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__CODE_BLOCK:
        return getCodeBlock();
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__PRAGMA_LIST:
        return getPragmaList();
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__RETURN_TYPE:
        return getReturnType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__SERVICE_VISIBILITY:
        setServiceVisibility((String)newValue);
        return;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__DOMAIN_NAME:
        setDomainName((DomainName)newValue);
        return;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__TERMINATOR_NAME:
        setTerminatorName((TerminatorName)newValue);
        return;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__SERVICE_NAME:
        setServiceName((ServiceName)newValue);
        return;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__PARAMETER_LIST:
        setParameterList((parameterList)newValue);
        return;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__CODE_BLOCK:
        setCodeBlock((CodeBlock)newValue);
        return;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__PRAGMA_LIST:
        setPragmaList((PragmaList)newValue);
        return;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__RETURN_TYPE:
        setReturnType((ReturnType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__SERVICE_VISIBILITY:
        setServiceVisibility(SERVICE_VISIBILITY_EDEFAULT);
        return;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__DOMAIN_NAME:
        setDomainName((DomainName)null);
        return;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__TERMINATOR_NAME:
        setTerminatorName((TerminatorName)null);
        return;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__SERVICE_NAME:
        setServiceName((ServiceName)null);
        return;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__PARAMETER_LIST:
        setParameterList((parameterList)null);
        return;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__CODE_BLOCK:
        setCodeBlock((CodeBlock)null);
        return;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__PRAGMA_LIST:
        setPragmaList((PragmaList)null);
        return;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__RETURN_TYPE:
        setReturnType((ReturnType)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__SERVICE_VISIBILITY:
        return SERVICE_VISIBILITY_EDEFAULT == null ? serviceVisibility != null : !SERVICE_VISIBILITY_EDEFAULT.equals(serviceVisibility);
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__DOMAIN_NAME:
        return domainName != null;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__TERMINATOR_NAME:
        return terminatorName != null;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__SERVICE_NAME:
        return serviceName != null;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__PARAMETER_LIST:
        return parameterList != null;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__CODE_BLOCK:
        return codeBlock != null;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__PRAGMA_LIST:
        return pragmaList != null;
      case MaslPackage.TERMINATOR_SERVICE_DEFINITION__RETURN_TYPE:
        return returnType != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (serviceVisibility: ");
    result.append(serviceVisibility);
    result.append(')');
    return result.toString();
  }

} //TerminatorServiceDefinitionImpl
