/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.masl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtuml.bp.xtext.masl.MaslPackage#getdefinition()
 * @model
 * @generated
 */
public interface definition extends EObject
{
} // definition
