/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.masl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>deprecated Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.xtext.masl.deprecatedType#getINSTANCE <em>INSTANCE</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.deprecatedType#getEVENT <em>EVENT</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.deprecatedType#getSERVICE <em>SERVICE</em>}</li>
 * </ul>
 *
 * @see org.xtuml.bp.xtext.masl.MaslPackage#getdeprecatedType()
 * @model
 * @generated
 */
public interface deprecatedType extends typeReference
{
  /**
   * Returns the value of the '<em><b>INSTANCE</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>INSTANCE</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>INSTANCE</em>' attribute.
   * @see #setINSTANCE(String)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getdeprecatedType_INSTANCE()
   * @model
   * @generated
   */
  String getINSTANCE();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.deprecatedType#getINSTANCE <em>INSTANCE</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>INSTANCE</em>' attribute.
   * @see #getINSTANCE()
   * @generated
   */
  void setINSTANCE(String value);

  /**
   * Returns the value of the '<em><b>EVENT</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>EVENT</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>EVENT</em>' attribute.
   * @see #setEVENT(String)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getdeprecatedType_EVENT()
   * @model
   * @generated
   */
  String getEVENT();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.deprecatedType#getEVENT <em>EVENT</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>EVENT</em>' attribute.
   * @see #getEVENT()
   * @generated
   */
  void setEVENT(String value);

  /**
   * Returns the value of the '<em><b>SERVICE</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>SERVICE</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>SERVICE</em>' attribute.
   * @see #setSERVICE(String)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getdeprecatedType_SERVICE()
   * @model
   * @generated
   */
  String getSERVICE();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.deprecatedType#getSERVICE <em>SERVICE</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>SERVICE</em>' attribute.
   * @see #getSERVICE()
   * @generated
   */
  void setSERVICE(String value);

} // deprecatedType
