/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.masl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtuml.bp.xtext.masl.MaslFactory
 * @model kind="package"
 * @generated
 */
public interface MaslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "masl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtuml.org/bp/xtext/Masl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "masl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MaslPackage eINSTANCE = org.xtuml.bp.xtext.masl.impl.MaslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.ProjectImpl <em>Project</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.ProjectImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getProject()
   * @generated
   */
  int PROJECT = 0;

  /**
   * The feature id for the '<em><b>Project Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__PROJECT_NAME = 0;

  /**
   * The feature id for the '<em><b>Project Item</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__PROJECT_ITEM = 1;

  /**
   * The feature id for the '<em><b>Pragma List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__PRAGMA_LIST = 2;

  /**
   * The number of structural features of the '<em>Project</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.projectItemImpl <em>project Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.projectItemImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getprojectItem()
   * @generated
   */
  int PROJECT_ITEM = 1;

  /**
   * The number of structural features of the '<em>project Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_ITEM_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.DomainImpl <em>Domain</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.DomainImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getDomain()
   * @generated
   */
  int DOMAIN = 2;

  /**
   * The feature id for the '<em><b>Domain Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN__DOMAIN_NAME = PROJECT_ITEM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Domain Prj Item</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN__DOMAIN_PRJ_ITEM = PROJECT_ITEM_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Pragma List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN__PRAGMA_LIST = PROJECT_ITEM_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Domain</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_FEATURE_COUNT = PROJECT_ITEM_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.domainPrjItemImpl <em>domain Prj Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.domainPrjItemImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getdomainPrjItem()
   * @generated
   */
  int DOMAIN_PRJ_ITEM = 3;

  /**
   * The number of structural features of the '<em>domain Prj Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_PRJ_ITEM_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.ProjectNameImpl <em>Project Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.ProjectNameImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getProjectName()
   * @generated
   */
  int PROJECT_NAME = 4;

  /**
   * The feature id for the '<em><b>Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_NAME__IDENTIFIER = 0;

  /**
   * The number of structural features of the '<em>Project Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.DomainNameImpl <em>Domain Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.DomainNameImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getDomainName()
   * @generated
   */
  int DOMAIN_NAME = 5;

  /**
   * The feature id for the '<em><b>Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_NAME__IDENTIFIER = 0;

  /**
   * The number of structural features of the '<em>Domain Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.TerminatorNameImpl <em>Terminator Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.TerminatorNameImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getTerminatorName()
   * @generated
   */
  int TERMINATOR_NAME = 6;

  /**
   * The feature id for the '<em><b>Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_NAME__IDENTIFIER = 0;

  /**
   * The number of structural features of the '<em>Terminator Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.TerminatorDefinitionImpl <em>Terminator Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.TerminatorDefinitionImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getTerminatorDefinition()
   * @generated
   */
  int TERMINATOR_DEFINITION = 7;

  /**
   * The feature id for the '<em><b>Terminator Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_DEFINITION__TERMINATOR_NAME = DOMAIN_PRJ_ITEM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Terminator Item</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_DEFINITION__TERMINATOR_ITEM = DOMAIN_PRJ_ITEM_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Pragma List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_DEFINITION__PRAGMA_LIST = DOMAIN_PRJ_ITEM_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Terminator Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_DEFINITION_FEATURE_COUNT = DOMAIN_PRJ_ITEM_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.terminatorItemImpl <em>terminator Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.terminatorItemImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getterminatorItem()
   * @generated
   */
  int TERMINATOR_ITEM = 8;

  /**
   * The feature id for the '<em><b>Service Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_ITEM__SERVICE_VISIBILITY = 0;

  /**
   * The feature id for the '<em><b>Service Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_ITEM__SERVICE_NAME = 1;

  /**
   * The feature id for the '<em><b>Parameter List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_ITEM__PARAMETER_LIST = 2;

  /**
   * The feature id for the '<em><b>Pragma List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_ITEM__PRAGMA_LIST = 3;

  /**
   * The number of structural features of the '<em>terminator Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_ITEM_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.TerminatorServiceDeclarationImpl <em>Terminator Service Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.TerminatorServiceDeclarationImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getTerminatorServiceDeclaration()
   * @generated
   */
  int TERMINATOR_SERVICE_DECLARATION = 9;

  /**
   * The feature id for the '<em><b>Service Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_SERVICE_DECLARATION__SERVICE_VISIBILITY = TERMINATOR_ITEM__SERVICE_VISIBILITY;

  /**
   * The feature id for the '<em><b>Service Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_SERVICE_DECLARATION__SERVICE_NAME = TERMINATOR_ITEM__SERVICE_NAME;

  /**
   * The feature id for the '<em><b>Parameter List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_SERVICE_DECLARATION__PARAMETER_LIST = TERMINATOR_ITEM__PARAMETER_LIST;

  /**
   * The feature id for the '<em><b>Pragma List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_SERVICE_DECLARATION__PRAGMA_LIST = TERMINATOR_ITEM__PRAGMA_LIST;

  /**
   * The number of structural features of the '<em>Terminator Service Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_SERVICE_DECLARATION_FEATURE_COUNT = TERMINATOR_ITEM_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.TerminatorFunctionDeclarationImpl <em>Terminator Function Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.TerminatorFunctionDeclarationImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getTerminatorFunctionDeclaration()
   * @generated
   */
  int TERMINATOR_FUNCTION_DECLARATION = 10;

  /**
   * The feature id for the '<em><b>Service Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_FUNCTION_DECLARATION__SERVICE_VISIBILITY = TERMINATOR_ITEM__SERVICE_VISIBILITY;

  /**
   * The feature id for the '<em><b>Service Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_FUNCTION_DECLARATION__SERVICE_NAME = TERMINATOR_ITEM__SERVICE_NAME;

  /**
   * The feature id for the '<em><b>Parameter List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_FUNCTION_DECLARATION__PARAMETER_LIST = TERMINATOR_ITEM__PARAMETER_LIST;

  /**
   * The feature id for the '<em><b>Pragma List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_FUNCTION_DECLARATION__PRAGMA_LIST = TERMINATOR_ITEM__PRAGMA_LIST;

  /**
   * The feature id for the '<em><b>Return Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_FUNCTION_DECLARATION__RETURN_TYPE = TERMINATOR_ITEM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Terminator Function Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERMINATOR_FUNCTION_DECLARATION_FEATURE_COUNT = TERMINATOR_ITEM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.parameterListImpl <em>parameter List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.parameterListImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getparameterList()
   * @generated
   */
  int PARAMETER_LIST = 11;

  /**
   * The feature id for the '<em><b>Parameter Definition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_LIST__PARAMETER_DEFINITION = 0;

  /**
   * The number of structural features of the '<em>parameter List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.ParameterDefinitionImpl <em>Parameter Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.ParameterDefinitionImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getParameterDefinition()
   * @generated
   */
  int PARAMETER_DEFINITION = 12;

  /**
   * The feature id for the '<em><b>Parameter Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_DEFINITION__PARAMETER_NAME = 0;

  /**
   * The feature id for the '<em><b>Parameter Mode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_DEFINITION__PARAMETER_MODE = 1;

  /**
   * The feature id for the '<em><b>Parameter Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_DEFINITION__PARAMETER_TYPE = 2;

  /**
   * The number of structural features of the '<em>Parameter Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_DEFINITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.ServiceNameImpl <em>Service Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.ServiceNameImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getServiceName()
   * @generated
   */
  int SERVICE_NAME = 13;

  /**
   * The feature id for the '<em><b>Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_NAME__IDENTIFIER = 0;

  /**
   * The number of structural features of the '<em>Service Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVICE_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.ParameterNameImpl <em>Parameter Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.ParameterNameImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getParameterName()
   * @generated
   */
  int PARAMETER_NAME = 14;

  /**
   * The feature id for the '<em><b>Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_NAME__IDENTIFIER = 0;

  /**
   * The number of structural features of the '<em>Parameter Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.ParameterTypeImpl <em>Parameter Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.ParameterTypeImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getParameterType()
   * @generated
   */
  int PARAMETER_TYPE = 15;

  /**
   * The feature id for the '<em><b>Type Reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_TYPE__TYPE_REFERENCE = 0;

  /**
   * The number of structural features of the '<em>Parameter Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.ReturnTypeImpl <em>Return Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.ReturnTypeImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getReturnType()
   * @generated
   */
  int RETURN_TYPE = 16;

  /**
   * The feature id for the '<em><b>Type Reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETURN_TYPE__TYPE_REFERENCE = 0;

  /**
   * The number of structural features of the '<em>Return Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETURN_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.typeReferenceImpl <em>type Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.typeReferenceImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#gettypeReference()
   * @generated
   */
  int TYPE_REFERENCE = 17;

  /**
   * The number of structural features of the '<em>type Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_REFERENCE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.NamedTypeImpl <em>Named Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.NamedTypeImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getNamedType()
   * @generated
   */
  int NAMED_TYPE = 18;

  /**
   * The feature id for the '<em><b>Anonymous</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMED_TYPE__ANONYMOUS = TYPE_REFERENCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Domain Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMED_TYPE__DOMAIN_NAME = TYPE_REFERENCE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Type Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMED_TYPE__TYPE_NAME = TYPE_REFERENCE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Named Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMED_TYPE_FEATURE_COUNT = TYPE_REFERENCE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.TypeNameImpl <em>Type Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.TypeNameImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getTypeName()
   * @generated
   */
  int TYPE_NAME = 19;

  /**
   * The feature id for the '<em><b>Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_NAME__IDENTIFIER = 0;

  /**
   * The number of structural features of the '<em>Type Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.PragmaListImpl <em>Pragma List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.PragmaListImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getPragmaList()
   * @generated
   */
  int PRAGMA_LIST = 20;

  /**
   * The feature id for the '<em><b>Pragma</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRAGMA_LIST__PRAGMA = 0;

  /**
   * The number of structural features of the '<em>Pragma List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRAGMA_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.PragmaImpl <em>Pragma</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.PragmaImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getPragma()
   * @generated
   */
  int PRAGMA = 21;

  /**
   * The feature id for the '<em><b>Pragma Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRAGMA__PRAGMA_NAME = 0;

  /**
   * The feature id for the '<em><b>Pragma Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRAGMA__PRAGMA_VALUE = 1;

  /**
   * The number of structural features of the '<em>Pragma</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRAGMA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtuml.bp.xtext.masl.impl.PragmaNameImpl <em>Pragma Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtuml.bp.xtext.masl.impl.PragmaNameImpl
   * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getPragmaName()
   * @generated
   */
  int PRAGMA_NAME = 22;

  /**
   * The feature id for the '<em><b>Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRAGMA_NAME__IDENTIFIER = 0;

  /**
   * The number of structural features of the '<em>Pragma Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRAGMA_NAME_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.Project <em>Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Project</em>'.
   * @see org.xtuml.bp.xtext.masl.Project
   * @generated
   */
  EClass getProject();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.Project#getProjectName <em>Project Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Project Name</em>'.
   * @see org.xtuml.bp.xtext.masl.Project#getProjectName()
   * @see #getProject()
   * @generated
   */
  EReference getProject_ProjectName();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtuml.bp.xtext.masl.Project#getProjectItem <em>Project Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Project Item</em>'.
   * @see org.xtuml.bp.xtext.masl.Project#getProjectItem()
   * @see #getProject()
   * @generated
   */
  EReference getProject_ProjectItem();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.Project#getPragmaList <em>Pragma List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pragma List</em>'.
   * @see org.xtuml.bp.xtext.masl.Project#getPragmaList()
   * @see #getProject()
   * @generated
   */
  EReference getProject_PragmaList();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.projectItem <em>project Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>project Item</em>'.
   * @see org.xtuml.bp.xtext.masl.projectItem
   * @generated
   */
  EClass getprojectItem();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.Domain <em>Domain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domain</em>'.
   * @see org.xtuml.bp.xtext.masl.Domain
   * @generated
   */
  EClass getDomain();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.Domain#getDomainName <em>Domain Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Domain Name</em>'.
   * @see org.xtuml.bp.xtext.masl.Domain#getDomainName()
   * @see #getDomain()
   * @generated
   */
  EReference getDomain_DomainName();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtuml.bp.xtext.masl.Domain#getDomainPrjItem <em>Domain Prj Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Domain Prj Item</em>'.
   * @see org.xtuml.bp.xtext.masl.Domain#getDomainPrjItem()
   * @see #getDomain()
   * @generated
   */
  EReference getDomain_DomainPrjItem();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.Domain#getPragmaList <em>Pragma List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pragma List</em>'.
   * @see org.xtuml.bp.xtext.masl.Domain#getPragmaList()
   * @see #getDomain()
   * @generated
   */
  EReference getDomain_PragmaList();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.domainPrjItem <em>domain Prj Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>domain Prj Item</em>'.
   * @see org.xtuml.bp.xtext.masl.domainPrjItem
   * @generated
   */
  EClass getdomainPrjItem();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.ProjectName <em>Project Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Project Name</em>'.
   * @see org.xtuml.bp.xtext.masl.ProjectName
   * @generated
   */
  EClass getProjectName();

  /**
   * Returns the meta object for the attribute '{@link org.xtuml.bp.xtext.masl.ProjectName#getIdentifier <em>Identifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Identifier</em>'.
   * @see org.xtuml.bp.xtext.masl.ProjectName#getIdentifier()
   * @see #getProjectName()
   * @generated
   */
  EAttribute getProjectName_Identifier();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.DomainName <em>Domain Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domain Name</em>'.
   * @see org.xtuml.bp.xtext.masl.DomainName
   * @generated
   */
  EClass getDomainName();

  /**
   * Returns the meta object for the attribute '{@link org.xtuml.bp.xtext.masl.DomainName#getIdentifier <em>Identifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Identifier</em>'.
   * @see org.xtuml.bp.xtext.masl.DomainName#getIdentifier()
   * @see #getDomainName()
   * @generated
   */
  EAttribute getDomainName_Identifier();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.TerminatorName <em>Terminator Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Terminator Name</em>'.
   * @see org.xtuml.bp.xtext.masl.TerminatorName
   * @generated
   */
  EClass getTerminatorName();

  /**
   * Returns the meta object for the attribute '{@link org.xtuml.bp.xtext.masl.TerminatorName#getIdentifier <em>Identifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Identifier</em>'.
   * @see org.xtuml.bp.xtext.masl.TerminatorName#getIdentifier()
   * @see #getTerminatorName()
   * @generated
   */
  EAttribute getTerminatorName_Identifier();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.TerminatorDefinition <em>Terminator Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Terminator Definition</em>'.
   * @see org.xtuml.bp.xtext.masl.TerminatorDefinition
   * @generated
   */
  EClass getTerminatorDefinition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.TerminatorDefinition#getTerminatorName <em>Terminator Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Terminator Name</em>'.
   * @see org.xtuml.bp.xtext.masl.TerminatorDefinition#getTerminatorName()
   * @see #getTerminatorDefinition()
   * @generated
   */
  EReference getTerminatorDefinition_TerminatorName();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtuml.bp.xtext.masl.TerminatorDefinition#getTerminatorItem <em>Terminator Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Terminator Item</em>'.
   * @see org.xtuml.bp.xtext.masl.TerminatorDefinition#getTerminatorItem()
   * @see #getTerminatorDefinition()
   * @generated
   */
  EReference getTerminatorDefinition_TerminatorItem();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.TerminatorDefinition#getPragmaList <em>Pragma List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pragma List</em>'.
   * @see org.xtuml.bp.xtext.masl.TerminatorDefinition#getPragmaList()
   * @see #getTerminatorDefinition()
   * @generated
   */
  EReference getTerminatorDefinition_PragmaList();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.terminatorItem <em>terminator Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>terminator Item</em>'.
   * @see org.xtuml.bp.xtext.masl.terminatorItem
   * @generated
   */
  EClass getterminatorItem();

  /**
   * Returns the meta object for the attribute '{@link org.xtuml.bp.xtext.masl.terminatorItem#getServiceVisibility <em>Service Visibility</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Service Visibility</em>'.
   * @see org.xtuml.bp.xtext.masl.terminatorItem#getServiceVisibility()
   * @see #getterminatorItem()
   * @generated
   */
  EAttribute getterminatorItem_ServiceVisibility();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.terminatorItem#getServiceName <em>Service Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Service Name</em>'.
   * @see org.xtuml.bp.xtext.masl.terminatorItem#getServiceName()
   * @see #getterminatorItem()
   * @generated
   */
  EReference getterminatorItem_ServiceName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.terminatorItem#getParameterList <em>Parameter List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameter List</em>'.
   * @see org.xtuml.bp.xtext.masl.terminatorItem#getParameterList()
   * @see #getterminatorItem()
   * @generated
   */
  EReference getterminatorItem_ParameterList();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.terminatorItem#getPragmaList <em>Pragma List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pragma List</em>'.
   * @see org.xtuml.bp.xtext.masl.terminatorItem#getPragmaList()
   * @see #getterminatorItem()
   * @generated
   */
  EReference getterminatorItem_PragmaList();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.TerminatorServiceDeclaration <em>Terminator Service Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Terminator Service Declaration</em>'.
   * @see org.xtuml.bp.xtext.masl.TerminatorServiceDeclaration
   * @generated
   */
  EClass getTerminatorServiceDeclaration();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.TerminatorFunctionDeclaration <em>Terminator Function Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Terminator Function Declaration</em>'.
   * @see org.xtuml.bp.xtext.masl.TerminatorFunctionDeclaration
   * @generated
   */
  EClass getTerminatorFunctionDeclaration();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.TerminatorFunctionDeclaration#getReturnType <em>Return Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Return Type</em>'.
   * @see org.xtuml.bp.xtext.masl.TerminatorFunctionDeclaration#getReturnType()
   * @see #getTerminatorFunctionDeclaration()
   * @generated
   */
  EReference getTerminatorFunctionDeclaration_ReturnType();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.parameterList <em>parameter List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>parameter List</em>'.
   * @see org.xtuml.bp.xtext.masl.parameterList
   * @generated
   */
  EClass getparameterList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtuml.bp.xtext.masl.parameterList#getParameterDefinition <em>Parameter Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameter Definition</em>'.
   * @see org.xtuml.bp.xtext.masl.parameterList#getParameterDefinition()
   * @see #getparameterList()
   * @generated
   */
  EReference getparameterList_ParameterDefinition();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.ParameterDefinition <em>Parameter Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter Definition</em>'.
   * @see org.xtuml.bp.xtext.masl.ParameterDefinition
   * @generated
   */
  EClass getParameterDefinition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.ParameterDefinition#getParameterName <em>Parameter Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameter Name</em>'.
   * @see org.xtuml.bp.xtext.masl.ParameterDefinition#getParameterName()
   * @see #getParameterDefinition()
   * @generated
   */
  EReference getParameterDefinition_ParameterName();

  /**
   * Returns the meta object for the attribute '{@link org.xtuml.bp.xtext.masl.ParameterDefinition#getParameterMode <em>Parameter Mode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Parameter Mode</em>'.
   * @see org.xtuml.bp.xtext.masl.ParameterDefinition#getParameterMode()
   * @see #getParameterDefinition()
   * @generated
   */
  EAttribute getParameterDefinition_ParameterMode();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.ParameterDefinition#getParameterType <em>Parameter Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameter Type</em>'.
   * @see org.xtuml.bp.xtext.masl.ParameterDefinition#getParameterType()
   * @see #getParameterDefinition()
   * @generated
   */
  EReference getParameterDefinition_ParameterType();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.ServiceName <em>Service Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Service Name</em>'.
   * @see org.xtuml.bp.xtext.masl.ServiceName
   * @generated
   */
  EClass getServiceName();

  /**
   * Returns the meta object for the attribute '{@link org.xtuml.bp.xtext.masl.ServiceName#getIdentifier <em>Identifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Identifier</em>'.
   * @see org.xtuml.bp.xtext.masl.ServiceName#getIdentifier()
   * @see #getServiceName()
   * @generated
   */
  EAttribute getServiceName_Identifier();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.ParameterName <em>Parameter Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter Name</em>'.
   * @see org.xtuml.bp.xtext.masl.ParameterName
   * @generated
   */
  EClass getParameterName();

  /**
   * Returns the meta object for the attribute '{@link org.xtuml.bp.xtext.masl.ParameterName#getIdentifier <em>Identifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Identifier</em>'.
   * @see org.xtuml.bp.xtext.masl.ParameterName#getIdentifier()
   * @see #getParameterName()
   * @generated
   */
  EAttribute getParameterName_Identifier();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.ParameterType <em>Parameter Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter Type</em>'.
   * @see org.xtuml.bp.xtext.masl.ParameterType
   * @generated
   */
  EClass getParameterType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.ParameterType#getTypeReference <em>Type Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type Reference</em>'.
   * @see org.xtuml.bp.xtext.masl.ParameterType#getTypeReference()
   * @see #getParameterType()
   * @generated
   */
  EReference getParameterType_TypeReference();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.ReturnType <em>Return Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Return Type</em>'.
   * @see org.xtuml.bp.xtext.masl.ReturnType
   * @generated
   */
  EClass getReturnType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.ReturnType#getTypeReference <em>Type Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type Reference</em>'.
   * @see org.xtuml.bp.xtext.masl.ReturnType#getTypeReference()
   * @see #getReturnType()
   * @generated
   */
  EReference getReturnType_TypeReference();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.typeReference <em>type Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>type Reference</em>'.
   * @see org.xtuml.bp.xtext.masl.typeReference
   * @generated
   */
  EClass gettypeReference();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.NamedType <em>Named Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Named Type</em>'.
   * @see org.xtuml.bp.xtext.masl.NamedType
   * @generated
   */
  EClass getNamedType();

  /**
   * Returns the meta object for the attribute '{@link org.xtuml.bp.xtext.masl.NamedType#getAnonymous <em>Anonymous</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Anonymous</em>'.
   * @see org.xtuml.bp.xtext.masl.NamedType#getAnonymous()
   * @see #getNamedType()
   * @generated
   */
  EAttribute getNamedType_Anonymous();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.NamedType#getDomainName <em>Domain Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Domain Name</em>'.
   * @see org.xtuml.bp.xtext.masl.NamedType#getDomainName()
   * @see #getNamedType()
   * @generated
   */
  EReference getNamedType_DomainName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.NamedType#getTypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type Name</em>'.
   * @see org.xtuml.bp.xtext.masl.NamedType#getTypeName()
   * @see #getNamedType()
   * @generated
   */
  EReference getNamedType_TypeName();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.TypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Name</em>'.
   * @see org.xtuml.bp.xtext.masl.TypeName
   * @generated
   */
  EClass getTypeName();

  /**
   * Returns the meta object for the attribute '{@link org.xtuml.bp.xtext.masl.TypeName#getIdentifier <em>Identifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Identifier</em>'.
   * @see org.xtuml.bp.xtext.masl.TypeName#getIdentifier()
   * @see #getTypeName()
   * @generated
   */
  EAttribute getTypeName_Identifier();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.PragmaList <em>Pragma List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pragma List</em>'.
   * @see org.xtuml.bp.xtext.masl.PragmaList
   * @generated
   */
  EClass getPragmaList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtuml.bp.xtext.masl.PragmaList#getPragma <em>Pragma</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pragma</em>'.
   * @see org.xtuml.bp.xtext.masl.PragmaList#getPragma()
   * @see #getPragmaList()
   * @generated
   */
  EReference getPragmaList_Pragma();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.Pragma <em>Pragma</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pragma</em>'.
   * @see org.xtuml.bp.xtext.masl.Pragma
   * @generated
   */
  EClass getPragma();

  /**
   * Returns the meta object for the containment reference '{@link org.xtuml.bp.xtext.masl.Pragma#getPragmaName <em>Pragma Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pragma Name</em>'.
   * @see org.xtuml.bp.xtext.masl.Pragma#getPragmaName()
   * @see #getPragma()
   * @generated
   */
  EReference getPragma_PragmaName();

  /**
   * Returns the meta object for the attribute list '{@link org.xtuml.bp.xtext.masl.Pragma#getPragmaValue <em>Pragma Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Pragma Value</em>'.
   * @see org.xtuml.bp.xtext.masl.Pragma#getPragmaValue()
   * @see #getPragma()
   * @generated
   */
  EAttribute getPragma_PragmaValue();

  /**
   * Returns the meta object for class '{@link org.xtuml.bp.xtext.masl.PragmaName <em>Pragma Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pragma Name</em>'.
   * @see org.xtuml.bp.xtext.masl.PragmaName
   * @generated
   */
  EClass getPragmaName();

  /**
   * Returns the meta object for the attribute '{@link org.xtuml.bp.xtext.masl.PragmaName#getIdentifier <em>Identifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Identifier</em>'.
   * @see org.xtuml.bp.xtext.masl.PragmaName#getIdentifier()
   * @see #getPragmaName()
   * @generated
   */
  EAttribute getPragmaName_Identifier();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MaslFactory getMaslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.ProjectImpl <em>Project</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.ProjectImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getProject()
     * @generated
     */
    EClass PROJECT = eINSTANCE.getProject();

    /**
     * The meta object literal for the '<em><b>Project Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECT__PROJECT_NAME = eINSTANCE.getProject_ProjectName();

    /**
     * The meta object literal for the '<em><b>Project Item</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECT__PROJECT_ITEM = eINSTANCE.getProject_ProjectItem();

    /**
     * The meta object literal for the '<em><b>Pragma List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECT__PRAGMA_LIST = eINSTANCE.getProject_PragmaList();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.projectItemImpl <em>project Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.projectItemImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getprojectItem()
     * @generated
     */
    EClass PROJECT_ITEM = eINSTANCE.getprojectItem();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.DomainImpl <em>Domain</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.DomainImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getDomain()
     * @generated
     */
    EClass DOMAIN = eINSTANCE.getDomain();

    /**
     * The meta object literal for the '<em><b>Domain Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAIN__DOMAIN_NAME = eINSTANCE.getDomain_DomainName();

    /**
     * The meta object literal for the '<em><b>Domain Prj Item</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAIN__DOMAIN_PRJ_ITEM = eINSTANCE.getDomain_DomainPrjItem();

    /**
     * The meta object literal for the '<em><b>Pragma List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAIN__PRAGMA_LIST = eINSTANCE.getDomain_PragmaList();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.domainPrjItemImpl <em>domain Prj Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.domainPrjItemImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getdomainPrjItem()
     * @generated
     */
    EClass DOMAIN_PRJ_ITEM = eINSTANCE.getdomainPrjItem();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.ProjectNameImpl <em>Project Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.ProjectNameImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getProjectName()
     * @generated
     */
    EClass PROJECT_NAME = eINSTANCE.getProjectName();

    /**
     * The meta object literal for the '<em><b>Identifier</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT_NAME__IDENTIFIER = eINSTANCE.getProjectName_Identifier();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.DomainNameImpl <em>Domain Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.DomainNameImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getDomainName()
     * @generated
     */
    EClass DOMAIN_NAME = eINSTANCE.getDomainName();

    /**
     * The meta object literal for the '<em><b>Identifier</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOMAIN_NAME__IDENTIFIER = eINSTANCE.getDomainName_Identifier();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.TerminatorNameImpl <em>Terminator Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.TerminatorNameImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getTerminatorName()
     * @generated
     */
    EClass TERMINATOR_NAME = eINSTANCE.getTerminatorName();

    /**
     * The meta object literal for the '<em><b>Identifier</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TERMINATOR_NAME__IDENTIFIER = eINSTANCE.getTerminatorName_Identifier();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.TerminatorDefinitionImpl <em>Terminator Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.TerminatorDefinitionImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getTerminatorDefinition()
     * @generated
     */
    EClass TERMINATOR_DEFINITION = eINSTANCE.getTerminatorDefinition();

    /**
     * The meta object literal for the '<em><b>Terminator Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMINATOR_DEFINITION__TERMINATOR_NAME = eINSTANCE.getTerminatorDefinition_TerminatorName();

    /**
     * The meta object literal for the '<em><b>Terminator Item</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMINATOR_DEFINITION__TERMINATOR_ITEM = eINSTANCE.getTerminatorDefinition_TerminatorItem();

    /**
     * The meta object literal for the '<em><b>Pragma List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMINATOR_DEFINITION__PRAGMA_LIST = eINSTANCE.getTerminatorDefinition_PragmaList();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.terminatorItemImpl <em>terminator Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.terminatorItemImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getterminatorItem()
     * @generated
     */
    EClass TERMINATOR_ITEM = eINSTANCE.getterminatorItem();

    /**
     * The meta object literal for the '<em><b>Service Visibility</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TERMINATOR_ITEM__SERVICE_VISIBILITY = eINSTANCE.getterminatorItem_ServiceVisibility();

    /**
     * The meta object literal for the '<em><b>Service Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMINATOR_ITEM__SERVICE_NAME = eINSTANCE.getterminatorItem_ServiceName();

    /**
     * The meta object literal for the '<em><b>Parameter List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMINATOR_ITEM__PARAMETER_LIST = eINSTANCE.getterminatorItem_ParameterList();

    /**
     * The meta object literal for the '<em><b>Pragma List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMINATOR_ITEM__PRAGMA_LIST = eINSTANCE.getterminatorItem_PragmaList();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.TerminatorServiceDeclarationImpl <em>Terminator Service Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.TerminatorServiceDeclarationImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getTerminatorServiceDeclaration()
     * @generated
     */
    EClass TERMINATOR_SERVICE_DECLARATION = eINSTANCE.getTerminatorServiceDeclaration();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.TerminatorFunctionDeclarationImpl <em>Terminator Function Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.TerminatorFunctionDeclarationImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getTerminatorFunctionDeclaration()
     * @generated
     */
    EClass TERMINATOR_FUNCTION_DECLARATION = eINSTANCE.getTerminatorFunctionDeclaration();

    /**
     * The meta object literal for the '<em><b>Return Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERMINATOR_FUNCTION_DECLARATION__RETURN_TYPE = eINSTANCE.getTerminatorFunctionDeclaration_ReturnType();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.parameterListImpl <em>parameter List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.parameterListImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getparameterList()
     * @generated
     */
    EClass PARAMETER_LIST = eINSTANCE.getparameterList();

    /**
     * The meta object literal for the '<em><b>Parameter Definition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER_LIST__PARAMETER_DEFINITION = eINSTANCE.getparameterList_ParameterDefinition();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.ParameterDefinitionImpl <em>Parameter Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.ParameterDefinitionImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getParameterDefinition()
     * @generated
     */
    EClass PARAMETER_DEFINITION = eINSTANCE.getParameterDefinition();

    /**
     * The meta object literal for the '<em><b>Parameter Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER_DEFINITION__PARAMETER_NAME = eINSTANCE.getParameterDefinition_ParameterName();

    /**
     * The meta object literal for the '<em><b>Parameter Mode</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER_DEFINITION__PARAMETER_MODE = eINSTANCE.getParameterDefinition_ParameterMode();

    /**
     * The meta object literal for the '<em><b>Parameter Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER_DEFINITION__PARAMETER_TYPE = eINSTANCE.getParameterDefinition_ParameterType();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.ServiceNameImpl <em>Service Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.ServiceNameImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getServiceName()
     * @generated
     */
    EClass SERVICE_NAME = eINSTANCE.getServiceName();

    /**
     * The meta object literal for the '<em><b>Identifier</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVICE_NAME__IDENTIFIER = eINSTANCE.getServiceName_Identifier();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.ParameterNameImpl <em>Parameter Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.ParameterNameImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getParameterName()
     * @generated
     */
    EClass PARAMETER_NAME = eINSTANCE.getParameterName();

    /**
     * The meta object literal for the '<em><b>Identifier</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER_NAME__IDENTIFIER = eINSTANCE.getParameterName_Identifier();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.ParameterTypeImpl <em>Parameter Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.ParameterTypeImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getParameterType()
     * @generated
     */
    EClass PARAMETER_TYPE = eINSTANCE.getParameterType();

    /**
     * The meta object literal for the '<em><b>Type Reference</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER_TYPE__TYPE_REFERENCE = eINSTANCE.getParameterType_TypeReference();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.ReturnTypeImpl <em>Return Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.ReturnTypeImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getReturnType()
     * @generated
     */
    EClass RETURN_TYPE = eINSTANCE.getReturnType();

    /**
     * The meta object literal for the '<em><b>Type Reference</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RETURN_TYPE__TYPE_REFERENCE = eINSTANCE.getReturnType_TypeReference();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.typeReferenceImpl <em>type Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.typeReferenceImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#gettypeReference()
     * @generated
     */
    EClass TYPE_REFERENCE = eINSTANCE.gettypeReference();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.NamedTypeImpl <em>Named Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.NamedTypeImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getNamedType()
     * @generated
     */
    EClass NAMED_TYPE = eINSTANCE.getNamedType();

    /**
     * The meta object literal for the '<em><b>Anonymous</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAMED_TYPE__ANONYMOUS = eINSTANCE.getNamedType_Anonymous();

    /**
     * The meta object literal for the '<em><b>Domain Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NAMED_TYPE__DOMAIN_NAME = eINSTANCE.getNamedType_DomainName();

    /**
     * The meta object literal for the '<em><b>Type Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NAMED_TYPE__TYPE_NAME = eINSTANCE.getNamedType_TypeName();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.TypeNameImpl <em>Type Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.TypeNameImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getTypeName()
     * @generated
     */
    EClass TYPE_NAME = eINSTANCE.getTypeName();

    /**
     * The meta object literal for the '<em><b>Identifier</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE_NAME__IDENTIFIER = eINSTANCE.getTypeName_Identifier();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.PragmaListImpl <em>Pragma List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.PragmaListImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getPragmaList()
     * @generated
     */
    EClass PRAGMA_LIST = eINSTANCE.getPragmaList();

    /**
     * The meta object literal for the '<em><b>Pragma</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRAGMA_LIST__PRAGMA = eINSTANCE.getPragmaList_Pragma();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.PragmaImpl <em>Pragma</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.PragmaImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getPragma()
     * @generated
     */
    EClass PRAGMA = eINSTANCE.getPragma();

    /**
     * The meta object literal for the '<em><b>Pragma Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRAGMA__PRAGMA_NAME = eINSTANCE.getPragma_PragmaName();

    /**
     * The meta object literal for the '<em><b>Pragma Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRAGMA__PRAGMA_VALUE = eINSTANCE.getPragma_PragmaValue();

    /**
     * The meta object literal for the '{@link org.xtuml.bp.xtext.masl.impl.PragmaNameImpl <em>Pragma Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtuml.bp.xtext.masl.impl.PragmaNameImpl
     * @see org.xtuml.bp.xtext.masl.impl.MaslPackageImpl#getPragmaName()
     * @generated
     */
    EClass PRAGMA_NAME = eINSTANCE.getPragmaName();

    /**
     * The meta object literal for the '<em><b>Identifier</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRAGMA_NAME__IDENTIFIER = eINSTANCE.getPragmaName_Identifier();

  }

} //MaslPackage
