/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.masl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.xtext.masl.ParameterDefinition#getParameterName <em>Parameter Name</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.ParameterDefinition#getParameterMode <em>Parameter Mode</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.ParameterDefinition#getParameterType <em>Parameter Type</em>}</li>
 * </ul>
 *
 * @see org.xtuml.bp.xtext.masl.MaslPackage#getParameterDefinition()
 * @model
 * @generated
 */
public interface ParameterDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Parameter Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameter Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter Name</em>' containment reference.
   * @see #setParameterName(ParameterName)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getParameterDefinition_ParameterName()
   * @model containment="true"
   * @generated
   */
  ParameterName getParameterName();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.ParameterDefinition#getParameterName <em>Parameter Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameter Name</em>' containment reference.
   * @see #getParameterName()
   * @generated
   */
  void setParameterName(ParameterName value);

  /**
   * Returns the value of the '<em><b>Parameter Mode</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameter Mode</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter Mode</em>' attribute.
   * @see #setParameterMode(String)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getParameterDefinition_ParameterMode()
   * @model
   * @generated
   */
  String getParameterMode();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.ParameterDefinition#getParameterMode <em>Parameter Mode</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameter Mode</em>' attribute.
   * @see #getParameterMode()
   * @generated
   */
  void setParameterMode(String value);

  /**
   * Returns the value of the '<em><b>Parameter Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameter Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter Type</em>' containment reference.
   * @see #setParameterType(ParameterType)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getParameterDefinition_ParameterType()
   * @model containment="true"
   * @generated
   */
  ParameterType getParameterType();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.ParameterDefinition#getParameterType <em>Parameter Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameter Type</em>' containment reference.
   * @see #getParameterType()
   * @generated
   */
  void setParameterType(ParameterType value);

} // ParameterDefinition
