/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.masl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pragma List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.xtext.masl.PragmaList#getPragma <em>Pragma</em>}</li>
 * </ul>
 *
 * @see org.xtuml.bp.xtext.masl.MaslPackage#getPragmaList()
 * @model
 * @generated
 */
public interface PragmaList extends EObject
{
  /**
   * Returns the value of the '<em><b>Pragma</b></em>' containment reference list.
   * The list contents are of type {@link org.xtuml.bp.xtext.masl.Pragma}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pragma</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pragma</em>' containment reference list.
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getPragmaList_Pragma()
   * @model containment="true"
   * @generated
   */
  EList<Pragma> getPragma();

} // PragmaList
