/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.masl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Project</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.xtext.masl.Project#getProjectName <em>Project Name</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.Project#getProjectItem <em>Project Item</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.Project#getPragmaList <em>Pragma List</em>}</li>
 * </ul>
 *
 * @see org.xtuml.bp.xtext.masl.MaslPackage#getProject()
 * @model
 * @generated
 */
public interface Project extends definition
{
  /**
   * Returns the value of the '<em><b>Project Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Project Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Project Name</em>' containment reference.
   * @see #setProjectName(ProjectName)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getProject_ProjectName()
   * @model containment="true"
   * @generated
   */
  ProjectName getProjectName();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.Project#getProjectName <em>Project Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Project Name</em>' containment reference.
   * @see #getProjectName()
   * @generated
   */
  void setProjectName(ProjectName value);

  /**
   * Returns the value of the '<em><b>Project Item</b></em>' containment reference list.
   * The list contents are of type {@link org.xtuml.bp.xtext.masl.projectItem}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Project Item</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Project Item</em>' containment reference list.
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getProject_ProjectItem()
   * @model containment="true"
   * @generated
   */
  EList<projectItem> getProjectItem();

  /**
   * Returns the value of the '<em><b>Pragma List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pragma List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pragma List</em>' containment reference.
   * @see #setPragmaList(PragmaList)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getProject_PragmaList()
   * @model containment="true"
   * @generated
   */
  PragmaList getPragmaList();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.Project#getPragmaList <em>Pragma List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pragma List</em>' containment reference.
   * @see #getPragmaList()
   * @generated
   */
  void setPragmaList(PragmaList value);

} // Project
