/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.masl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Return Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.xtext.masl.ReturnType#getTypeReference <em>Type Reference</em>}</li>
 * </ul>
 *
 * @see org.xtuml.bp.xtext.masl.MaslPackage#getReturnType()
 * @model
 * @generated
 */
public interface ReturnType extends EObject
{
  /**
   * Returns the value of the '<em><b>Type Reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Reference</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Reference</em>' containment reference.
   * @see #setTypeReference(typeReference)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getReturnType_TypeReference()
   * @model containment="true"
   * @generated
   */
  typeReference getTypeReference();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.ReturnType#getTypeReference <em>Type Reference</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Reference</em>' containment reference.
   * @see #getTypeReference()
   * @generated
   */
  void setTypeReference(typeReference value);

} // ReturnType
