/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.masl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>service Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.xtext.masl.serviceType#getINSTANCE <em>INSTANCE</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.serviceType#getRelationshipName <em>Relationship Name</em>}</li>
 * </ul>
 *
 * @see org.xtuml.bp.xtext.masl.MaslPackage#getserviceType()
 * @model
 * @generated
 */
public interface serviceType extends EObject
{
  /**
   * Returns the value of the '<em><b>INSTANCE</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>INSTANCE</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>INSTANCE</em>' attribute.
   * @see #setINSTANCE(String)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getserviceType_INSTANCE()
   * @model
   * @generated
   */
  String getINSTANCE();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.serviceType#getINSTANCE <em>INSTANCE</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>INSTANCE</em>' attribute.
   * @see #getINSTANCE()
   * @generated
   */
  void setINSTANCE(String value);

  /**
   * Returns the value of the '<em><b>Relationship Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Relationship Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relationship Name</em>' containment reference.
   * @see #setRelationshipName(RelationshipName)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getserviceType_RelationshipName()
   * @model containment="true"
   * @generated
   */
  RelationshipName getRelationshipName();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.serviceType#getRelationshipName <em>Relationship Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relationship Name</em>' containment reference.
   * @see #getRelationshipName()
   * @generated
   */
  void setRelationshipName(RelationshipName value);

} // serviceType
