/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.masl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Terminator Service Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.xtext.masl.TerminatorServiceDefinition#getServiceVisibility <em>Service Visibility</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.TerminatorServiceDefinition#getDomainName <em>Domain Name</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.TerminatorServiceDefinition#getTerminatorName <em>Terminator Name</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.TerminatorServiceDefinition#getServiceName <em>Service Name</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.TerminatorServiceDefinition#getParameterList <em>Parameter List</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.TerminatorServiceDefinition#getCodeBlock <em>Code Block</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.TerminatorServiceDefinition#getPragmaList <em>Pragma List</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.TerminatorServiceDefinition#getReturnType <em>Return Type</em>}</li>
 * </ul>
 *
 * @see org.xtuml.bp.xtext.masl.MaslPackage#getTerminatorServiceDefinition()
 * @model
 * @generated
 */
public interface TerminatorServiceDefinition extends definition
{
  /**
   * Returns the value of the '<em><b>Service Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Service Visibility</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Service Visibility</em>' attribute.
   * @see #setServiceVisibility(String)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getTerminatorServiceDefinition_ServiceVisibility()
   * @model
   * @generated
   */
  String getServiceVisibility();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.TerminatorServiceDefinition#getServiceVisibility <em>Service Visibility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Service Visibility</em>' attribute.
   * @see #getServiceVisibility()
   * @generated
   */
  void setServiceVisibility(String value);

  /**
   * Returns the value of the '<em><b>Domain Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Domain Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Domain Name</em>' containment reference.
   * @see #setDomainName(DomainName)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getTerminatorServiceDefinition_DomainName()
   * @model containment="true"
   * @generated
   */
  DomainName getDomainName();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.TerminatorServiceDefinition#getDomainName <em>Domain Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Domain Name</em>' containment reference.
   * @see #getDomainName()
   * @generated
   */
  void setDomainName(DomainName value);

  /**
   * Returns the value of the '<em><b>Terminator Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Terminator Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Terminator Name</em>' containment reference.
   * @see #setTerminatorName(TerminatorName)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getTerminatorServiceDefinition_TerminatorName()
   * @model containment="true"
   * @generated
   */
  TerminatorName getTerminatorName();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.TerminatorServiceDefinition#getTerminatorName <em>Terminator Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Terminator Name</em>' containment reference.
   * @see #getTerminatorName()
   * @generated
   */
  void setTerminatorName(TerminatorName value);

  /**
   * Returns the value of the '<em><b>Service Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Service Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Service Name</em>' containment reference.
   * @see #setServiceName(ServiceName)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getTerminatorServiceDefinition_ServiceName()
   * @model containment="true"
   * @generated
   */
  ServiceName getServiceName();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.TerminatorServiceDefinition#getServiceName <em>Service Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Service Name</em>' containment reference.
   * @see #getServiceName()
   * @generated
   */
  void setServiceName(ServiceName value);

  /**
   * Returns the value of the '<em><b>Parameter List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameter List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter List</em>' containment reference.
   * @see #setParameterList(parameterList)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getTerminatorServiceDefinition_ParameterList()
   * @model containment="true"
   * @generated
   */
  parameterList getParameterList();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.TerminatorServiceDefinition#getParameterList <em>Parameter List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameter List</em>' containment reference.
   * @see #getParameterList()
   * @generated
   */
  void setParameterList(parameterList value);

  /**
   * Returns the value of the '<em><b>Code Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Code Block</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code Block</em>' containment reference.
   * @see #setCodeBlock(CodeBlock)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getTerminatorServiceDefinition_CodeBlock()
   * @model containment="true"
   * @generated
   */
  CodeBlock getCodeBlock();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.TerminatorServiceDefinition#getCodeBlock <em>Code Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code Block</em>' containment reference.
   * @see #getCodeBlock()
   * @generated
   */
  void setCodeBlock(CodeBlock value);

  /**
   * Returns the value of the '<em><b>Pragma List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pragma List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pragma List</em>' containment reference.
   * @see #setPragmaList(PragmaList)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getTerminatorServiceDefinition_PragmaList()
   * @model containment="true"
   * @generated
   */
  PragmaList getPragmaList();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.TerminatorServiceDefinition#getPragmaList <em>Pragma List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pragma List</em>' containment reference.
   * @see #getPragmaList()
   * @generated
   */
  void setPragmaList(PragmaList value);

  /**
   * Returns the value of the '<em><b>Return Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Return Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Return Type</em>' containment reference.
   * @see #setReturnType(ReturnType)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getTerminatorServiceDefinition_ReturnType()
   * @model containment="true"
   * @generated
   */
  ReturnType getReturnType();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.TerminatorServiceDefinition#getReturnType <em>Return Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Return Type</em>' containment reference.
   * @see #getReturnType()
   * @generated
   */
  void setReturnType(ReturnType value);

} // TerminatorServiceDefinition
