/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.masl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>terminator Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.xtext.masl.terminatorItem#getServiceVisibility <em>Service Visibility</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.terminatorItem#getServiceName <em>Service Name</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.terminatorItem#getParameterList <em>Parameter List</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.terminatorItem#getPragmaList <em>Pragma List</em>}</li>
 * </ul>
 *
 * @see org.xtuml.bp.xtext.masl.MaslPackage#getterminatorItem()
 * @model
 * @generated
 */
public interface terminatorItem extends EObject
{
  /**
   * Returns the value of the '<em><b>Service Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Service Visibility</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Service Visibility</em>' attribute.
   * @see #setServiceVisibility(String)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getterminatorItem_ServiceVisibility()
   * @model
   * @generated
   */
  String getServiceVisibility();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.terminatorItem#getServiceVisibility <em>Service Visibility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Service Visibility</em>' attribute.
   * @see #getServiceVisibility()
   * @generated
   */
  void setServiceVisibility(String value);

  /**
   * Returns the value of the '<em><b>Service Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Service Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Service Name</em>' containment reference.
   * @see #setServiceName(ServiceName)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getterminatorItem_ServiceName()
   * @model containment="true"
   * @generated
   */
  ServiceName getServiceName();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.terminatorItem#getServiceName <em>Service Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Service Name</em>' containment reference.
   * @see #getServiceName()
   * @generated
   */
  void setServiceName(ServiceName value);

  /**
   * Returns the value of the '<em><b>Parameter List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameter List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter List</em>' containment reference.
   * @see #setParameterList(parameterList)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getterminatorItem_ParameterList()
   * @model containment="true"
   * @generated
   */
  parameterList getParameterList();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.terminatorItem#getParameterList <em>Parameter List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameter List</em>' containment reference.
   * @see #getParameterList()
   * @generated
   */
  void setParameterList(parameterList value);

  /**
   * Returns the value of the '<em><b>Pragma List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pragma List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pragma List</em>' containment reference.
   * @see #setPragmaList(PragmaList)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getterminatorItem_PragmaList()
   * @model containment="true"
   * @generated
   */
  PragmaList getPragmaList();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.terminatorItem#getPragmaList <em>Pragma List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pragma List</em>' containment reference.
   * @see #getPragmaList()
   * @generated
   */
  void setPragmaList(PragmaList value);

} // terminatorItem
