/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.masl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Terminator Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.bp.xtext.masl.TerminatorDefinition#getTerminatorName <em>Terminator Name</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.TerminatorDefinition#getTerminatorItem <em>Terminator Item</em>}</li>
 *   <li>{@link org.xtuml.bp.xtext.masl.TerminatorDefinition#getPragmaList <em>Pragma List</em>}</li>
 * </ul>
 *
 * @see org.xtuml.bp.xtext.masl.MaslPackage#getTerminatorDefinition()
 * @model
 * @generated
 */
public interface TerminatorDefinition extends domainPrjItem
{
  /**
   * Returns the value of the '<em><b>Terminator Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Terminator Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Terminator Name</em>' containment reference.
   * @see #setTerminatorName(TerminatorName)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getTerminatorDefinition_TerminatorName()
   * @model containment="true"
   * @generated
   */
  TerminatorName getTerminatorName();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.TerminatorDefinition#getTerminatorName <em>Terminator Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Terminator Name</em>' containment reference.
   * @see #getTerminatorName()
   * @generated
   */
  void setTerminatorName(TerminatorName value);

  /**
   * Returns the value of the '<em><b>Terminator Item</b></em>' containment reference list.
   * The list contents are of type {@link org.xtuml.bp.xtext.masl.terminatorItem}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Terminator Item</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Terminator Item</em>' containment reference list.
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getTerminatorDefinition_TerminatorItem()
   * @model containment="true"
   * @generated
   */
  EList<terminatorItem> getTerminatorItem();

  /**
   * Returns the value of the '<em><b>Pragma List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pragma List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pragma List</em>' containment reference.
   * @see #setPragmaList(PragmaList)
   * @see org.xtuml.bp.xtext.masl.MaslPackage#getTerminatorDefinition_PragmaList()
   * @model containment="true"
   * @generated
   */
  PragmaList getPragmaList();

  /**
   * Sets the value of the '{@link org.xtuml.bp.xtext.masl.TerminatorDefinition#getPragmaList <em>Pragma List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pragma List</em>' containment reference.
   * @see #getPragmaList()
   * @generated
   */
  void setPragmaList(PragmaList value);

} // TerminatorDefinition
