/**
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.masl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Terminator Service Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtuml.bp.xtext.masl.MaslPackage#getTerminatorServiceDeclaration()
 * @model
 * @generated
 */
public interface TerminatorServiceDeclaration extends terminatorItem
{
} // TerminatorServiceDeclaration
