/*
 * generated by Xtext 2.9.1
 */
package org.xtuml.bp.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtuml.bp.xtext.parser.antlr.internal.InternalMaslParser;
import org.xtuml.bp.xtext.services.MaslGrammarAccess;

public class MaslParser extends AbstractAntlrParser {

	@Inject
	private MaslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMaslParser createParser(XtextTokenStream stream) {
		return new InternalMaslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "projectDefinition";
	}

	public MaslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MaslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
